package gitserver

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"time"

	"github.com/sageox/ox/internal/endpoint"
	"github.com/sageox/ox/internal/logger"
	"github.com/sageox/ox/internal/version"
)

// AgentsMDOptions configures AGENTS.md generation.
type AgentsMDOptions struct {
	// RepoURL is the linked repository URL (optional)
	RepoURL string

	// TeamID is the team identifier (optional)
	TeamID string

	// Endpoint is the SageOx API endpoint (optional, defaults to production)
	Endpoint string

	// RepoType is the type of repository ("ledger" or "team-context")
	RepoType string
}

// CreateAgentsMD creates an AGENTS.md file in the cloned ledger repository.
// This file explains the repository's purpose to AI agents and humans.
// Commits and pushes the file if the repo has a remote.
func CreateAgentsMD(ctx context.Context, repoPath string, opts *AgentsMDOptions) error {
	agentsPath := filepath.Join(repoPath, "AGENTS.md")

	// skip if already exists
	if _, err := os.Stat(agentsPath); err == nil {
		logger.Debug("AGENTS.md already exists", "path", agentsPath)
		return nil
	}

	// generate content
	content := generateAgentsMDContent(opts)

	// write file
	if err := os.WriteFile(agentsPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write AGENTS.md: %w", err)
	}
	logger.Info("created AGENTS.md", "path", agentsPath)

	// commit and push
	if err := commitAndPushAgentsMD(ctx, repoPath); err != nil {
		// non-fatal: file is created locally even if push fails
		logger.Warn("failed to commit/push AGENTS.md", "error", err)
	}

	return nil
}

// generateAgentsMDContent creates the AGENTS.md content with dynamic values.
func generateAgentsMDContent(opts *AgentsMDOptions) string {
	if opts == nil {
		opts = &AgentsMDOptions{}
	}

	ep := opts.Endpoint
	if ep == "" {
		ep = endpoint.Get()
	}

	repoURL := opts.RepoURL
	if repoURL == "" {
		repoURL = "(not linked)"
	}

	teamID := opts.TeamID
	if teamID == "" {
		teamID = "(personal)"
	}

	repoType := opts.RepoType
	if repoType == "" {
		repoType = "ledger"
	}

	// determine description based on repo type
	var description string
	switch repoType {
	case "team-context":
		description = "This repository is a **Team Context** repository managed by SageOx."
	default:
		description = "This repository is a **Ledger** managed by SageOx."
	}

	return fmt.Sprintf(`# SageOx Repository

%s

## Purpose

- Stores ambient context for AI coding agents
- Syncs team knowledge and project state
- Enables persistent agent sessions

## Structure

- `+"`sessions/`"+` - Agent session data
- `+"`context/`"+` - Shared context files
- `+"`history/`"+` - Conversation history

## Linked Repository

This repository is linked to: %s

## Team

- **Team ID:** %s
- **Endpoint:** %s

## Usage

This repository is managed automatically by the `+"`ox`"+` CLI.
Manual edits may be overwritten during sync.

---
*Generated by SageOx CLI v%s at %s*
`, description, repoURL, teamID, ep, version.Version, time.Now().UTC().Format(time.RFC3339))
}

// commitAndPushAgentsMD commits the AGENTS.md file and pushes to remote.
func commitAndPushAgentsMD(ctx context.Context, repoPath string) error {
	// check if remote exists
	remoteCmd := exec.CommandContext(ctx, "git", "-C", repoPath, "remote")
	output, err := remoteCmd.Output()
	if err != nil || len(output) == 0 {
		// no remote, skip push
		return commitAgentsMD(ctx, repoPath)
	}

	// commit first
	if err := commitAgentsMD(ctx, repoPath); err != nil {
		return err
	}

	// push
	pushCmd := exec.CommandContext(ctx, "git", "-C", repoPath, "push", "--quiet")
	if err := pushCmd.Run(); err != nil {
		return fmt.Errorf("push: %w", err)
	}

	logger.Info("pushed AGENTS.md to remote")
	return nil
}

// commitAgentsMD commits the AGENTS.md file.
func commitAgentsMD(ctx context.Context, repoPath string) error {
	// add file
	addCmd := exec.CommandContext(ctx, "git", "-C", repoPath, "add", "AGENTS.md")
	if err := addCmd.Run(); err != nil {
		return fmt.Errorf("git add: %w", err)
	}

	// commit
	commitCmd := exec.CommandContext(ctx, "git", "-C", repoPath, "commit", "-m", "docs: add AGENTS.md repository documentation")
	if output, err := commitCmd.CombinedOutput(); err != nil {
		// might fail if nothing to commit (already added)
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) && exitErr.ExitCode() == 1 {
			logger.Debug("AGENTS.md already committed or no changes")
			return nil
		}
		return fmt.Errorf("git commit: %w: %s", err, output)
	}

	logger.Info("committed AGENTS.md")
	return nil
}
