package attest

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/google/uuid"
)

// AttestationVersion is the wire version of the record. It lives in the
// FILENAME as well (`<capability>.v1.json`) so a reader told "I speak v1" never
// has to open a v2 object to discover it cannot read it.
const AttestationVersion = 1

// attestationsSubdir is where records live inside the corpus, beside the
// features they attest.
//
// Deliberately the PRODUCT repo, not the Ledger. Three reasons, all load-bearing:
// the Ledger is migrating off git to Lore and every tree added to it is
// migration surface; a re-proof storm would fan out to one GitLab commit per
// capability, which is how the 2026-03-11 thundering-herd incident happened; and
// a record beside the `.feature` it attests inherits commit signing, branch
// protection, and content addressing for free — in the one substrate where
// SageOx holds no mutating credential on the customer's copy.
const attestationsSubdir = "attestations"

const attestationIDPrefix = "att_"

// Verdict values for a proof. Three states, never a boolean.
//
// The two-state version is the failure mode this whole record exists to prevent:
// in the six worked proofs of PR #2763, four were clean, one landed on the wrong
// step, and one revealed a second gate nobody knew about. A counter that reported
// "6 attested" would have been wrong three different ways.
const (
	// ProofClean — the break produced a failure on the step that names the claim.
	ProofClean = "clean"
	// ProofAmbiguous — it went red, but not where the claim lives. The scenario
	// proves something; it does not prove THIS.
	ProofAmbiguous = "ambiguous"
	// ProofInconclusive — the break produced no failure at all. That is a finding
	// about the check, not about the product.
	ProofInconclusive = "inconclusive"
)

// Subject schemes. The discriminated union is cheap insurance against the
// Ledger's git → Lore migration: a record typed "bound to commit abc123" is
// unresolvable the day the substrate changes, and "bound to a commit" is the
// one property that cannot be dropped without the record decaying into ordinary
// test reporting.
const (
	SchemeGitCommit = "git-commit"
	SchemeLoreCID   = "lore-cid"
)

// Attestation is a falsifiable claim about customer-visible behavior, carrying
// its own proof that the check has teeth.
//
// NOT REDERIVABLE. Every other artifact in this repo can be regenerated by
// re-running something. This one cannot: it records a failure produced by a
// break that no longer exists in the tree. A field absent at mint time can only
// be recovered by re-applying that break at the original commit — frequently
// against an environment that no longer builds. Mint it complete or lose it.
type Attestation struct {
	Version       int    `json:"version"`
	AttestationID string `json:"attestationId"`
	// CapabilityID is `<domain>/<feature>#<rule-slug>` — the Gherkin Rule this
	// record attests. Derived from the corpus, never hand-authored.
	CapabilityID string `json:"capabilityId"`
	// Claim is the Rule text verbatim: a sentence a customer would recognize.
	Claim string `json:"claim"`
	// RepoKey is opaque and project-configured. No SageOx identifiers.
	RepoKey string `json:"repoKey"`
	// Subject is the tree this proof is valid for.
	Subject  TreeRef `json:"subject"`
	MintedAt string  `json:"mintedAt"`

	Proof Proof `json:"proof"`

	// SpecFingerprint is the compiled plan's fingerprint at mint time — the
	// spec-drift half of freshness.
	SpecFingerprint string `json:"specFingerprint,omitempty"`
	// ObservedSurface is what the run actually touched.
	//
	// Named for what it IS, not for what we wish it were. The honest alternative
	// name — "exercised closure" — would imply a product-source closure that has
	// no producer anywhere in either repo. Minting a name we cannot honor is the
	// exact theater this record exists to prevent.
	ObservedSurface ObservedSurface `json:"observedSurface"`

	Evidence []EvidenceRef `json:"evidence,omitempty"`
	// Signature is unused while the record lives in git, which already provides
	// content addressing, commit signing, and branch protection — and is the one
	// substrate where we hold no write credential on the customer's copy.
	// It becomes REQUIRED the day a record is written anywhere we can rewrite it.
	Signature *Signature `json:"signature,omitempty"`
}

// TreeRef identifies the tree a proof is valid for, substrate-agnostically.
type TreeRef struct {
	Scheme string `json:"scheme"`
	Value  string `json:"value"`
}

// Proof is the falsifiability evidence — the part that cannot be rederived.
type Proof struct {
	Verdict     string      `json:"verdict"`
	Break       Break       `json:"break"`
	ObservedRed ObservedRed `json:"observedRed"`
	RedRunID    string      `json:"redRunId"`
	GreenRunID  string      `json:"greenRunId"`
}

// Break is the adversarial change applied to make the claim false.
type Break struct {
	// Description is what was broken, in the language of the claim
	// ("team gate inverted — checkTeamAccess returns true for every caller").
	Description string `json:"description"`
	// DiffDigest is a sha256 over the applied patch. Its job is to prove a break
	// actually existed — without it, "we broke it and it went red" is unfalsifiable.
	DiffDigest string `json:"diffDigest,omitempty"`
	// TargetSurfaces are the surfaces the break was aimed at.
	TargetSurfaces []string `json:"targetSurfaces,omitempty"`
}

// ObservedRed is the failure the break produced, recorded verbatim.
type ObservedRed struct {
	// Verbatim is the assertion text exactly as the run emitted it.
	//
	// NEVER repaired, re-worded, or tidied. A cleaned-up error is edited
	// evidence, and this field exists to BE evidence.
	Verbatim  string `json:"verbatim"`
	StepIndex int    `json:"stepIndex"`
	StepText  string `json:"stepText"`
	// LandedOnClaimStep is the difference between a proof and a coincidence.
	// False forces Verdict to ambiguous — enforced in the parser, not by
	// convention, because convention is what lets "4 clean + 1 ambiguous" get
	// quietly rounded up to "5 proven".
	LandedOnClaimStep bool `json:"landedOnClaimStep"`
}

// ObservedSurface is what the run touched, at a stated granularity.
type ObservedSurface struct {
	// Granularity is stated rather than implied so a later, finer producer is
	// additive instead of a migration.
	//
	// "route" over-invalidates: a CSS change on a page marks that page's auth
	// attestation stale. That direction is deliberate — a false stale costs one
	// re-run, a false fresh is the lie the product exists to prevent.
	Granularity string    `json:"granularity"`
	Surfaces    []Surface `json:"surfaces,omitempty"`
}

// Surface is one observed surface pinned to a content digest.
type Surface struct {
	SurfaceID     string `json:"surfaceId"`
	ContentDigest string `json:"contentDigest,omitempty"`
}

// EvidenceRef points at a stored artifact WITHOUT naming a provider.
//
// No s3:// scheme, no bucket, no region, no presigned URL. Resolution is config.
// That single discipline is the entire cost of keeping bring-your-own-bucket a
// two-way door — and the first customer to ask is as likely to want GCS or MinIO
// as S3.
type EvidenceRef struct {
	StoreID string `json:"storeId"`
	Key     string `json:"key"`
	SHA256  string `json:"sha256,omitempty"`
	Bytes   int64  `json:"bytes,omitempty"`
	Kind    string `json:"kind"`
	// Redacted is false for screenshots today, and that is the honest value.
	// The redactor is text-only by design: a capture of a signed-in surface
	// still shows the user menu. Any display of this evidence must render the
	// warning as visible copy, never as a quiet flag.
	Redacted bool `json:"redacted"`
}

// Signature is a detached signature over the canonicalized record.
type Signature struct {
	Alg   string `json:"alg"`
	KeyID string `json:"keyId"`
	Sig   string `json:"sig"`
}

// GenerateAttestationID mints a time-sortable `att_<UUIDv7>` id, matching the
// pln_/ses_/repo_ convention already used across ox.
func GenerateAttestationID() string {
	return attestationIDPrefix + uuid.Must(uuid.NewV7()).String()
}

var (
	// ErrAmbiguousMislabeled is the one semantic rule the parser enforces.
	ErrAmbiguousMislabeled = errors.New(
		"proof.observedRed.landedOnClaimStep is false, so proof.verdict must be \"ambiguous\" — " +
			"a red that landed away from the step naming the claim is not a clean proof")
	// ErrVersionMismatch gates the wire version before shape validation.
	ErrVersionMismatch = errors.New("unsupported attestation version")
)

// ParseAttestation decodes a record at the trust boundary: version gate first,
// then STRICT shape (unknown fields rejected), then the semantic rule.
//
// Strict rather than lenient because a field this record silently ignored is a
// field a future reader will assume was honored.
func ParseAttestation(raw []byte) (*Attestation, error) {
	// Version-gate before shape so a v2 record fails with "unsupported version"
	// rather than a confusing pile of unknown-field errors.
	var probe struct {
		Version int `json:"version"`
	}
	if err := json.Unmarshal(raw, &probe); err != nil {
		return nil, fmt.Errorf("parse attestation: %w", err)
	}
	if probe.Version != AttestationVersion {
		return nil, fmt.Errorf("%w: got %d, want %d", ErrVersionMismatch, probe.Version, AttestationVersion)
	}

	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	var a Attestation
	if err := dec.Decode(&a); err != nil {
		return nil, fmt.Errorf("parse attestation: %w", err)
	}
	if err := a.Validate(); err != nil {
		return nil, err
	}
	return &a, nil
}

// Validate enforces the invariants that make a record trustworthy.
func (a *Attestation) Validate() error {
	if a == nil {
		return errors.New("attestation is nil")
	}
	if a.Version != AttestationVersion {
		return fmt.Errorf("attestation version is %d, want %d", a.Version, AttestationVersion)
	}
	if strings.TrimSpace(a.AttestationID) == "" {
		return errors.New("attestation has no attestationId")
	}
	if strings.TrimSpace(a.CapabilityID) == "" {
		return errors.New("attestation has no capabilityId")
	}
	if strings.TrimSpace(a.Claim) == "" {
		return errors.New("attestation has no claim")
	}
	if err := validateRepoKey(a.RepoKey); err != nil {
		return fmt.Errorf("attestation repoKey: %w", err)
	}
	if strings.TrimSpace(a.Subject.Value) == "" {
		return errors.New("attestation has no subject — a proof not bound to a tree proves nothing")
	}
	switch a.Subject.Scheme {
	case SchemeGitCommit, SchemeLoreCID:
	default:
		return fmt.Errorf("attestation subject scheme %q is not one of %q, %q",
			a.Subject.Scheme, SchemeGitCommit, SchemeLoreCID)
	}
	if a.MintedAt == "" {
		return errors.New("attestation has no mintedAt")
	}
	if _, err := time.Parse(time.RFC3339, a.MintedAt); err != nil {
		return fmt.Errorf("attestation mintedAt is not RFC3339: %w", err)
	}
	switch a.Proof.Verdict {
	case ProofClean, ProofAmbiguous, ProofInconclusive:
	default:
		return fmt.Errorf("attestation verdict %q is not one of %q, %q, %q",
			a.Proof.Verdict, ProofClean, ProofAmbiguous, ProofInconclusive)
	}
	if strings.TrimSpace(a.Proof.Break.Description) == "" {
		return errors.New("attestation proof has no break description")
	}
	if strings.TrimSpace(a.Proof.RedRunID) == "" {
		return errors.New("attestation proof has no redRunId")
	}
	if strings.TrimSpace(a.Proof.RedRunID) != a.Proof.RedRunID {
		return errors.New("attestation proof redRunId has leading or trailing whitespace")
	}
	if strings.TrimSpace(a.Proof.GreenRunID) == "" {
		return errors.New("attestation proof has no greenRunId")
	}
	if strings.TrimSpace(a.Proof.GreenRunID) != a.Proof.GreenRunID {
		return errors.New("attestation proof greenRunId has leading or trailing whitespace")
	}
	if a.Proof.RedRunID == a.Proof.GreenRunID {
		return errors.New("attestation proof redRunId and greenRunId must identify different runs")
	}
	if a.Proof.Verdict != ProofInconclusive && a.Proof.ObservedRed.Verbatim == "" {
		return errors.New("attestation records a red verdict with no verbatim failure text")
	}
	if a.Proof.Verdict != ProofInconclusive && a.Proof.ObservedRed.StepIndex < 1 {
		return errors.New("attestation records a red verdict with no 1-indexed failure step")
	}
	if a.Proof.Verdict != ProofInconclusive && strings.TrimSpace(a.Proof.ObservedRed.StepText) == "" {
		return errors.New("attestation records a red verdict with no failure step text")
	}
	// THE rule. Enforced here so it cannot be honored inconsistently by callers.
	if !a.Proof.ObservedRed.LandedOnClaimStep && a.Proof.Verdict == ProofClean {
		return ErrAmbiguousMislabeled
	}
	return nil
}

// IsProof reports whether this record actually proves its claim. Only a clean
// verdict counts — ambiguous and inconclusive are findings, not proofs.
func (a *Attestation) IsProof() bool {
	return a != nil && a.Proof.Verdict == ProofClean
}

// Records is every attestation in a corpus, keyed by capability id.
type Records struct {
	byCapability map[string]*Attestation
	// Count is how many unique capability records were loaded. During the
	// filename migration a legacy slug file and its canonical encoded file may
	// coexist; the canonical record wins and the pair counts once.
	Count int
	// Invalid maps a file path to the reason it could not be read. Surfaced
	// rather than swallowed: a record we cannot parse is a capability whose
	// proof silently disappears, which reads identically to never having been
	// proven at all.
	Invalid map[string]string
}

// LoadRecords reads corpusRoot/attestations/**/*.v1.json.
//
// A missing attestations/ directory is not an error — it is the state every
// repo is in today, and it must render as "nothing proven yet" rather than as a
// failure to answer.
func LoadRecords(corpusRoot string) (*Records, error) {
	recs := &Records{byCapability: map[string]*Attestation{}, Invalid: map[string]string{}}
	canonical := map[string]bool{}
	dir := filepath.Join(corpusRoot, attestationsSubdir)
	if _, err := os.Stat(dir); err != nil {
		if os.IsNotExist(err) {
			return recs, nil
		}
		return nil, fmt.Errorf("read attestations: %w", err)
	}

	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error { //nolint:gosec // local corpus scan; parse/validation remains the trust boundary
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(d.Name(), ".json") {
			return nil
		}
		raw, readErr := os.ReadFile(path) //nolint:gosec // path comes from walking a caller-supplied corpus dir
		if readErr != nil {
			recs.Invalid[path] = readErr.Error()
			return nil
		}
		a, parseErr := ParseAttestation(raw)
		if parseErr != nil {
			recs.Invalid[path] = parseErr.Error()
			return nil
		}
		_, isCanonical := capabilityIDFromRecordFilename(d.Name())
		isCanonical = isCanonical && d.Name() == recordFilename(a.CapabilityID)
		if _, exists := recs.byCapability[a.CapabilityID]; !exists || isCanonical || !canonical[a.CapabilityID] {
			recs.byCapability[a.CapabilityID] = a
			canonical[a.CapabilityID] = isCanonical
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	recs.Count = len(recs.byCapability)
	return recs, nil
}

// For returns the record attesting a capability, if one exists.
func (r *Records) For(capabilityID string) (*Attestation, bool) {
	if r == nil {
		return nil, false
	}
	a, ok := r.byCapability[capabilityID]
	return a, ok
}

// All returns every valid record ordered by capability id. Callers that need
// to detect records whose capability left the current corpus must not have to
// reach into the internal index or silently lose those orphaned records.
func (r *Records) All() []*Attestation {
	if r == nil {
		return nil
	}
	ids := make([]string, 0, len(r.byCapability))
	for id := range r.byCapability {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	out := make([]*Attestation, 0, len(ids))
	for _, id := range ids {
		if a := r.byCapability[id]; a != nil {
			out = append(out, a)
		}
	}
	return out
}

// RecordPath is where a capability's record lives: one file per capability,
// current record only. The capability id is raw-URL-base64 encoded, making the
// mapping reversible and collision-free while keeping it one safe path segment.
//
// The path carries NO attestation id. History is git's job — duplicating it in
// the path defeats `git log --follow` and grows the tree without bound.
func RecordPath(corpusRoot, capabilityID string) string {
	return filepath.Join(corpusRoot, attestationsSubdir, recordFilename(capabilityID))
}

const recordFilenamePrefix = "cap-"

func recordFilename(capabilityID string) string {
	encoded := encodedPathSegment(capabilityID)
	return fmt.Sprintf("%s%s.v%d.json", recordFilenamePrefix, encoded, AttestationVersion)
}

func encodedPathSegment(value string) string {
	return base64.RawURLEncoding.EncodeToString([]byte(value))
}

func capabilityIDFromRecordFilename(name string) (string, bool) {
	suffix := fmt.Sprintf(".v%d.json", AttestationVersion)
	if !strings.HasPrefix(name, recordFilenamePrefix) || !strings.HasSuffix(name, suffix) {
		return "", false
	}
	encoded := strings.TrimSuffix(strings.TrimPrefix(name, recordFilenamePrefix), suffix)
	raw, err := base64.RawURLEncoding.DecodeString(encoded)
	if err != nil || len(raw) == 0 {
		return "", false
	}
	return string(raw), true
}

// WriteRecord validates then writes a record, creating parent directories.
// Validation happens BEFORE the write so an invalid record can never land.
func WriteRecord(corpusRoot string, a *Attestation) (string, error) {
	if err := a.Validate(); err != nil {
		return "", err
	}
	path := RecordPath(corpusRoot, a.CapabilityID)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", fmt.Errorf("create attestations dir: %w", err)
	}
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	if err := enc.Encode(a); err != nil {
		return "", fmt.Errorf("encode attestation: %w", err)
	}
	if err := os.WriteFile(path, buf.Bytes(), 0o600); err != nil {
		return "", fmt.Errorf("write attestation: %w", err)
	}
	return path, nil
}
