// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blobs.sql

package codedbsqlc

import (
	"context"
	"database/sql"
)

const getBlobIDByHash = `-- name: GetBlobIDByHash :one
SELECT id FROM blobs WHERE content_hash = ?
`

func (q *Queries) GetBlobIDByHash(ctx context.Context, contentHash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBlobIDByHash, contentHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertBlob = `-- name: InsertBlob :exec
INSERT OR IGNORE INTO blobs (content_hash, language) VALUES (?, ?)
`

type InsertBlobParams struct {
	ContentHash string         `json:"content_hash"`
	Language    sql.NullString `json:"language"`
}

func (q *Queries) InsertBlob(ctx context.Context, arg InsertBlobParams) error {
	_, err := q.db.ExecContext(ctx, insertBlob, arg.ContentHash, arg.Language)
	return err
}

const markBlobCommentsParsed = `-- name: MarkBlobCommentsParsed :exec
UPDATE blobs SET comments_parsed = 1 WHERE id = ?
`

func (q *Queries) MarkBlobCommentsParsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markBlobCommentsParsed, id)
	return err
}

const markBlobParsed = `-- name: MarkBlobParsed :exec
UPDATE blobs SET parsed = 1 WHERE id = ?
`

func (q *Queries) MarkBlobParsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markBlobParsed, id)
	return err
}
