// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commits.sql

package codedbsqlc

import (
	"context"
	"database/sql"
)

const getCommitIDByHash = `-- name: GetCommitIDByHash :one
SELECT id FROM commits WHERE hash = ?
`

func (q *Queries) GetCommitIDByHash(ctx context.Context, hash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCommitIDByHash, hash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertCommit = `-- name: InsertCommit :exec
INSERT OR IGNORE INTO commits (repo_id, hash, author, message, timestamp)
VALUES (?, ?, ?, ?, ?)
`

type InsertCommitParams struct {
	RepoID    int64          `json:"repo_id"`
	Hash      string         `json:"hash"`
	Author    sql.NullString `json:"author"`
	Message   sql.NullString `json:"message"`
	Timestamp sql.NullInt64  `json:"timestamp"`
}

func (q *Queries) InsertCommit(ctx context.Context, arg InsertCommitParams) error {
	_, err := q.db.ExecContext(ctx, insertCommit,
		arg.RepoID,
		arg.Hash,
		arg.Author,
		arg.Message,
		arg.Timestamp,
	)
	return err
}

const insertCommitParent = `-- name: InsertCommitParent :exec
INSERT OR IGNORE INTO commit_parents (commit_id, parent_id) VALUES (?, ?)
`

type InsertCommitParentParams struct {
	CommitID int64 `json:"commit_id"`
	ParentID int64 `json:"parent_id"`
}

func (q *Queries) InsertCommitParent(ctx context.Context, arg InsertCommitParentParams) error {
	_, err := q.db.ExecContext(ctx, insertCommitParent, arg.CommitID, arg.ParentID)
	return err
}
