// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diffs.sql

package codedbsqlc

import (
	"context"
	"database/sql"
)

const getDiffIDByCommitPath = `-- name: GetDiffIDByCommitPath :one
SELECT id FROM diffs WHERE commit_id = ? AND path = ?
`

type GetDiffIDByCommitPathParams struct {
	CommitID int64  `json:"commit_id"`
	Path     string `json:"path"`
}

func (q *Queries) GetDiffIDByCommitPath(ctx context.Context, arg GetDiffIDByCommitPathParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDiffIDByCommitPath, arg.CommitID, arg.Path)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDiff = `-- name: InsertDiff :exec
INSERT OR IGNORE INTO diffs (commit_id, path, old_blob_id, new_blob_id) VALUES (?, ?, ?, ?)
`

type InsertDiffParams struct {
	CommitID  int64         `json:"commit_id"`
	Path      string        `json:"path"`
	OldBlobID sql.NullInt64 `json:"old_blob_id"`
	NewBlobID sql.NullInt64 `json:"new_blob_id"`
}

func (q *Queries) InsertDiff(ctx context.Context, arg InsertDiffParams) error {
	_, err := q.db.ExecContext(ctx, insertDiff,
		arg.CommitID,
		arg.Path,
		arg.OldBlobID,
		arg.NewBlobID,
	)
	return err
}
