// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_revs.sql

package codedbsqlc

import (
	"context"
)

const deleteFileRevsByCommit = `-- name: DeleteFileRevsByCommit :exec
DELETE FROM file_revs WHERE commit_id = ?
`

func (q *Queries) DeleteFileRevsByCommit(ctx context.Context, commitID int64) error {
	_, err := q.db.ExecContext(ctx, deleteFileRevsByCommit, commitID)
	return err
}

const insertFileRev = `-- name: InsertFileRev :exec
INSERT OR IGNORE INTO file_revs (commit_id, path, blob_id) VALUES (?, ?, ?)
`

type InsertFileRevParams struct {
	CommitID int64  `json:"commit_id"`
	Path     string `json:"path"`
	BlobID   int64  `json:"blob_id"`
}

func (q *Queries) InsertFileRev(ctx context.Context, arg InsertFileRevParams) error {
	_, err := q.db.ExecContext(ctx, insertFileRev, arg.CommitID, arg.Path, arg.BlobID)
	return err
}
