// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github.sql

package codedbsqlc

import (
	"context"
	"database/sql"
)

const deleteIssue = `-- name: DeleteIssue :exec
DELETE FROM issues WHERE id = ?
`

func (q *Queries) DeleteIssue(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIssue, id)
	return err
}

const deleteIssueCommentsByIssue = `-- name: DeleteIssueCommentsByIssue :exec
DELETE FROM issue_comments WHERE issue_id = ?
`

func (q *Queries) DeleteIssueCommentsByIssue(ctx context.Context, issueID int64) error {
	_, err := q.db.ExecContext(ctx, deleteIssueCommentsByIssue, issueID)
	return err
}

const deletePRCommentsByPR = `-- name: DeletePRCommentsByPR :exec
DELETE FROM pr_comments WHERE pr_id = ?
`

func (q *Queries) DeletePRCommentsByPR(ctx context.Context, prID int64) error {
	_, err := q.db.ExecContext(ctx, deletePRCommentsByPR, prID)
	return err
}

const deletePRCommitsByPR = `-- name: DeletePRCommitsByPR :exec
DELETE FROM pr_commits WHERE pr_id = ?
`

func (q *Queries) DeletePRCommitsByPR(ctx context.Context, prID int64) error {
	_, err := q.db.ExecContext(ctx, deletePRCommitsByPR, prID)
	return err
}

const deletePullRequest = `-- name: DeletePullRequest :exec
DELETE FROM pull_requests WHERE id = ?
`

func (q *Queries) DeletePullRequest(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePullRequest, id)
	return err
}

const getIssueIDByNumber = `-- name: GetIssueIDByNumber :one
SELECT id FROM issues WHERE number = ?
`

func (q *Queries) GetIssueIDByNumber(ctx context.Context, number int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getIssueIDByNumber, number)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPRIDByNumber = `-- name: GetPRIDByNumber :one
SELECT id FROM pull_requests WHERE number = ?
`

func (q *Queries) GetPRIDByNumber(ctx context.Context, number int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPRIDByNumber, number)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIssue = `-- name: InsertIssue :execresult
INSERT INTO issues
    (number, title, body, author, state, labels, created_at, closed_at, updated_at, url, source_path)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertIssueParams struct {
	Number     int64          `json:"number"`
	Title      string         `json:"title"`
	Body       sql.NullString `json:"body"`
	Author     sql.NullString `json:"author"`
	State      string         `json:"state"`
	Labels     sql.NullString `json:"labels"`
	CreatedAt  sql.NullInt64  `json:"created_at"`
	ClosedAt   sql.NullInt64  `json:"closed_at"`
	UpdatedAt  sql.NullInt64  `json:"updated_at"`
	Url        sql.NullString `json:"url"`
	SourcePath sql.NullString `json:"source_path"`
}

func (q *Queries) InsertIssue(ctx context.Context, arg InsertIssueParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertIssue,
		arg.Number,
		arg.Title,
		arg.Body,
		arg.Author,
		arg.State,
		arg.Labels,
		arg.CreatedAt,
		arg.ClosedAt,
		arg.UpdatedAt,
		arg.Url,
		arg.SourcePath,
	)
}

const insertIssueComment = `-- name: InsertIssueComment :exec
INSERT INTO issue_comments (issue_id, author, body, created_at) VALUES (?, ?, ?, ?)
`

type InsertIssueCommentParams struct {
	IssueID   int64          `json:"issue_id"`
	Author    sql.NullString `json:"author"`
	Body      sql.NullString `json:"body"`
	CreatedAt sql.NullInt64  `json:"created_at"`
}

func (q *Queries) InsertIssueComment(ctx context.Context, arg InsertIssueCommentParams) error {
	_, err := q.db.ExecContext(ctx, insertIssueComment,
		arg.IssueID,
		arg.Author,
		arg.Body,
		arg.CreatedAt,
	)
	return err
}

const insertPRComment = `-- name: InsertPRComment :exec
INSERT INTO pr_comments (pr_id, author, body, path, line, created_at) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertPRCommentParams struct {
	PrID      int64          `json:"pr_id"`
	Author    sql.NullString `json:"author"`
	Body      sql.NullString `json:"body"`
	Path      sql.NullString `json:"path"`
	Line      sql.NullInt64  `json:"line"`
	CreatedAt sql.NullInt64  `json:"created_at"`
}

func (q *Queries) InsertPRComment(ctx context.Context, arg InsertPRCommentParams) error {
	_, err := q.db.ExecContext(ctx, insertPRComment,
		arg.PrID,
		arg.Author,
		arg.Body,
		arg.Path,
		arg.Line,
		arg.CreatedAt,
	)
	return err
}

const insertPRCommit = `-- name: InsertPRCommit :exec
INSERT INTO pr_commits (pr_id, sha) VALUES (?, ?)
`

type InsertPRCommitParams struct {
	PrID int64  `json:"pr_id"`
	Sha  string `json:"sha"`
}

func (q *Queries) InsertPRCommit(ctx context.Context, arg InsertPRCommitParams) error {
	_, err := q.db.ExecContext(ctx, insertPRCommit, arg.PrID, arg.Sha)
	return err
}

const insertPullRequest = `-- name: InsertPullRequest :execresult
INSERT INTO pull_requests
    (number, title, body, author, state, labels, created_at, merged_at, closed_at, updated_at, merge_commit, url, source_path)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPullRequestParams struct {
	Number      int64          `json:"number"`
	Title       string         `json:"title"`
	Body        sql.NullString `json:"body"`
	Author      sql.NullString `json:"author"`
	State       string         `json:"state"`
	Labels      sql.NullString `json:"labels"`
	CreatedAt   sql.NullInt64  `json:"created_at"`
	MergedAt    sql.NullInt64  `json:"merged_at"`
	ClosedAt    sql.NullInt64  `json:"closed_at"`
	UpdatedAt   sql.NullInt64  `json:"updated_at"`
	MergeCommit sql.NullString `json:"merge_commit"`
	Url         sql.NullString `json:"url"`
	SourcePath  sql.NullString `json:"source_path"`
}

func (q *Queries) InsertPullRequest(ctx context.Context, arg InsertPullRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertPullRequest,
		arg.Number,
		arg.Title,
		arg.Body,
		arg.Author,
		arg.State,
		arg.Labels,
		arg.CreatedAt,
		arg.MergedAt,
		arg.ClosedAt,
		arg.UpdatedAt,
		arg.MergeCommit,
		arg.Url,
		arg.SourcePath,
	)
}

const listFileMtimes = `-- name: ListFileMtimes :many
SELECT source_path, mtime_unix FROM github_file_mtimes
`

func (q *Queries) ListFileMtimes(ctx context.Context) ([]GithubFileMtime, error) {
	rows, err := q.db.QueryContext(ctx, listFileMtimes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubFileMtime{}
	for rows.Next() {
		var i GithubFileMtime
		if err := rows.Scan(&i.SourcePath, &i.MtimeUnix); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFileMtime = `-- name: UpsertFileMtime :exec
INSERT OR REPLACE INTO github_file_mtimes (source_path, mtime_unix) VALUES (?, ?)
`

type UpsertFileMtimeParams struct {
	SourcePath string `json:"source_path"`
	MtimeUnix  int64  `json:"mtime_unix"`
}

func (q *Queries) UpsertFileMtime(ctx context.Context, arg UpsertFileMtimeParams) error {
	_, err := q.db.ExecContext(ctx, upsertFileMtime, arg.SourcePath, arg.MtimeUnix)
	return err
}
