// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package codedbsqlc

import (
	"database/sql"
)

type Blob struct {
	ID             int64          `json:"id"`
	ContentHash    string         `json:"content_hash"`
	Language       sql.NullString `json:"language"`
	Parsed         int64          `json:"parsed"`
	CommentsParsed int64          `json:"comments_parsed"`
}

type Comment struct {
	ID      int64  `json:"id"`
	BlobID  int64  `json:"blob_id"`
	Text    string `json:"text"`
	Kind    string `json:"kind"`
	Line    int64  `json:"line"`
	EndLine int64  `json:"end_line"`
	Col     int64  `json:"col"`
	EndCol  int64  `json:"end_col"`
}

type Commit struct {
	ID        int64          `json:"id"`
	RepoID    int64          `json:"repo_id"`
	Hash      string         `json:"hash"`
	Author    sql.NullString `json:"author"`
	Message   sql.NullString `json:"message"`
	Timestamp sql.NullInt64  `json:"timestamp"`
}

type CommitParent struct {
	CommitID int64 `json:"commit_id"`
	ParentID int64 `json:"parent_id"`
}

type Diff struct {
	ID        int64         `json:"id"`
	CommitID  int64         `json:"commit_id"`
	Path      string        `json:"path"`
	OldBlobID sql.NullInt64 `json:"old_blob_id"`
	NewBlobID sql.NullInt64 `json:"new_blob_id"`
}

type FileRev struct {
	ID       int64  `json:"id"`
	CommitID int64  `json:"commit_id"`
	Path     string `json:"path"`
	BlobID   int64  `json:"blob_id"`
}

type GithubFileMtime struct {
	SourcePath string `json:"source_path"`
	MtimeUnix  int64  `json:"mtime_unix"`
}

type Issue struct {
	ID         int64          `json:"id"`
	Number     int64          `json:"number"`
	Title      string         `json:"title"`
	Body       sql.NullString `json:"body"`
	Author     sql.NullString `json:"author"`
	State      string         `json:"state"`
	Labels     sql.NullString `json:"labels"`
	CreatedAt  sql.NullInt64  `json:"created_at"`
	ClosedAt   sql.NullInt64  `json:"closed_at"`
	UpdatedAt  sql.NullInt64  `json:"updated_at"`
	Url        sql.NullString `json:"url"`
	SourcePath sql.NullString `json:"source_path"`
}

type IssueComment struct {
	ID        int64          `json:"id"`
	IssueID   int64          `json:"issue_id"`
	Author    sql.NullString `json:"author"`
	Body      sql.NullString `json:"body"`
	CreatedAt sql.NullInt64  `json:"created_at"`
}

type PrComment struct {
	ID        int64          `json:"id"`
	PrID      int64          `json:"pr_id"`
	Author    sql.NullString `json:"author"`
	Body      sql.NullString `json:"body"`
	Path      sql.NullString `json:"path"`
	Line      sql.NullInt64  `json:"line"`
	CreatedAt sql.NullInt64  `json:"created_at"`
}

type PrCommit struct {
	ID   int64  `json:"id"`
	PrID int64  `json:"pr_id"`
	Sha  string `json:"sha"`
}

type PullRequest struct {
	ID          int64          `json:"id"`
	Number      int64          `json:"number"`
	Title       string         `json:"title"`
	Body        sql.NullString `json:"body"`
	Author      sql.NullString `json:"author"`
	State       string         `json:"state"`
	Labels      sql.NullString `json:"labels"`
	CreatedAt   sql.NullInt64  `json:"created_at"`
	MergedAt    sql.NullInt64  `json:"merged_at"`
	ClosedAt    sql.NullInt64  `json:"closed_at"`
	UpdatedAt   sql.NullInt64  `json:"updated_at"`
	MergeCommit sql.NullString `json:"merge_commit"`
	Url         sql.NullString `json:"url"`
	SourcePath  sql.NullString `json:"source_path"`
}

type Ref struct {
	ID       int64  `json:"id"`
	RepoID   int64  `json:"repo_id"`
	Name     string `json:"name"`
	CommitID int64  `json:"commit_id"`
}

type Repo struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Path string `json:"path"`
}

type Symbol struct {
	ID         int64          `json:"id"`
	BlobID     int64          `json:"blob_id"`
	ParentID   sql.NullInt64  `json:"parent_id"`
	Name       string         `json:"name"`
	Kind       string         `json:"kind"`
	Line       int64          `json:"line"`
	Col        int64          `json:"col"`
	EndLine    sql.NullInt64  `json:"end_line"`
	EndCol     sql.NullInt64  `json:"end_col"`
	Signature  sql.NullString `json:"signature"`
	ReturnType sql.NullString `json:"return_type"`
	Params     sql.NullString `json:"params"`
}

type SymbolRef struct {
	ID       int64         `json:"id"`
	BlobID   int64         `json:"blob_id"`
	SymbolID sql.NullInt64 `json:"symbol_id"`
	RefName  string        `json:"ref_name"`
	Kind     string        `json:"kind"`
	Line     int64         `json:"line"`
	Col      int64         `json:"col"`
}
