// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refs.sql

package codedbsqlc

import (
	"context"
)

const upsertRef = `-- name: UpsertRef :exec
INSERT INTO refs (repo_id, name, commit_id) VALUES (?, ?, ?)
ON CONFLICT(repo_id, name) DO UPDATE SET commit_id = excluded.commit_id
`

type UpsertRefParams struct {
	RepoID   int64  `json:"repo_id"`
	Name     string `json:"name"`
	CommitID int64  `json:"commit_id"`
}

func (q *Queries) UpsertRef(ctx context.Context, arg UpsertRefParams) error {
	_, err := q.db.ExecContext(ctx, upsertRef, arg.RepoID, arg.Name, arg.CommitID)
	return err
}
