// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package codedbsqlc

import (
	"context"
)

const getRepoIDByName = `-- name: GetRepoIDByName :one
SELECT id FROM repos WHERE name = ?
`

func (q *Queries) GetRepoIDByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRepoIDByName, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCommitHashesByRepo = `-- name: ListCommitHashesByRepo :many
SELECT hash FROM commits WHERE repo_id = ?
`

func (q *Queries) ListCommitHashesByRepo(ctx context.Context, repoID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCommitHashesByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var hash string
		if err := rows.Scan(&hash); err != nil {
			return nil, err
		}
		items = append(items, hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefsByRepo = `-- name: ListRefsByRepo :many
SELECT r.name, c.hash FROM refs r JOIN commits c ON r.commit_id = c.id WHERE r.repo_id = ?
`

type ListRefsByRepoRow struct {
	Name string `json:"name"`
	Hash string `json:"hash"`
}

func (q *Queries) ListRefsByRepo(ctx context.Context, repoID int64) ([]ListRefsByRepoRow, error) {
	rows, err := q.db.QueryContext(ctx, listRefsByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRefsByRepoRow{}
	for rows.Next() {
		var i ListRefsByRepoRow
		if err := rows.Scan(&i.Name, &i.Hash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoPaths = `-- name: ListRepoPaths :many
SELECT path FROM repos
`

func (q *Queries) ListRepoPaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRepoPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRepo = `-- name: UpsertRepo :exec
INSERT INTO repos (name, path) VALUES (?, ?)
ON CONFLICT(name) DO UPDATE SET path = excluded.path
`

type UpsertRepoParams struct {
	Name string `json:"name"`
	Path string `json:"path"`
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) error {
	_, err := q.db.ExecContext(ctx, upsertRepo, arg.Name, arg.Path)
	return err
}
