// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: symbols.sql

package codedbsqlc

import (
	"context"
	"database/sql"
)

const updateSymbolParent = `-- name: UpdateSymbolParent :exec
UPDATE symbols SET parent_id = ? WHERE id = ?
`

type UpdateSymbolParentParams struct {
	ParentID sql.NullInt64 `json:"parent_id"`
	ID       int64         `json:"id"`
}

func (q *Queries) UpdateSymbolParent(ctx context.Context, arg UpdateSymbolParentParams) error {
	_, err := q.db.ExecContext(ctx, updateSymbolParent, arg.ParentID, arg.ID)
	return err
}
