// Code generated by sageox-design. DO NOT EDIT.
//
// Source: https://github.com/sageox/sageox-design
// Token file: tokens/colors.yaml
// Generated: 2026-08-25
// Regenerate: cd ../sageox-design && npm run sync
//
// This file provides the unified SageOx brand color palette for CLI output.
// All CLI styling should reference these constants rather than hardcoding colors.

package theme

import (
	lipgloss "charm.land/lipgloss/v2"
	"charm.land/lipgloss/v2/compat"
)

// Brand colors
const (
	BrandPrimary   = "#7aaa77"
	BrandSecondary = "#adcfa3"
	BrandNeutral   = "#111518"
)

// Adaptive colors for light/dark terminal detection
var (
	ColorPrimary = compat.AdaptiveColor{
		Light: lipgloss.Color("#3D643B"),
		Dark:  lipgloss.Color("#7AAA77"),
	}
	ColorSecondary = compat.AdaptiveColor{
		Light: lipgloss.Color("#324F31"),
		Dark:  lipgloss.Color("#ADCFA3"),
	}
	ColorAccent = compat.AdaptiveColor{
		Light: lipgloss.Color("#4E7D4C"),
		Dark:  lipgloss.Color("#99C693"),
	}
	ColorSuccess = compat.AdaptiveColor{
		Light: lipgloss.Color("#3D643B"),
		Dark:  lipgloss.Color("#7AAA77"),
	}
	ColorWarning = compat.AdaptiveColor{
		Light: lipgloss.Color("#A5842F"),
		Dark:  lipgloss.Color("#D9B654"),
	}
	ColorError = compat.AdaptiveColor{
		Light: lipgloss.Color("#9F4838"),
		Dark:  lipgloss.Color("#D77E6C"),
	}
	ColorInfo = compat.AdaptiveColor{
		Light: lipgloss.Color("#5580A0"),
		Dark:  lipgloss.Color("#7FA7C8"),
	}
	ColorDim = compat.AdaptiveColor{
		Light: lipgloss.Color("#6B7580"),
		Dark:  lipgloss.Color("#8F99A3"),
	}

	// Visibility semantic colors (from sageox-mono tokens.css)
	// Public uses teal scale, private uses amber/warn scale
	ColorPublic = compat.AdaptiveColor{
		Light: lipgloss.Color("#0f766e"), // ox-public-700
		Dark:  lipgloss.Color("#2dd4bf"), // ox-public-400
	}
	ColorPrivate = compat.AdaptiveColor{
		Light: lipgloss.Color("#b45309"), // ox-warn-700
		Dark:  lipgloss.Color("#fbbf24"), // ox-warn-400
	}

	// Wordmark two-tone colors (from sageox-design SVGs)
	ColorWordmarkSage = compat.AdaptiveColor{
		Light: lipgloss.Color("#7a8f78"), // Sage 500
		Dark:  lipgloss.Color("#c4d1c0"), // Sage 300
	}
	ColorWordmarkOx = compat.AdaptiveColor{
		Light: lipgloss.Color("#546a54"), // Sage 700
		Dark:  lipgloss.Color("#7a8f78"), // Sage 500
	}
)

// ANSI 256 color codes for maximum terminal compatibility
const (
	AnsiSuccess   = "82"
	AnsiPreserved = "39"
	AnsiError     = "196"
	AnsiWarning   = "214"
	AnsiInfo      = "39"
	AnsiHint      = "241"
	AnsiCode      = "213"
)

// Hex color constants (dark terminal/theme optimized)
const (
	HexPrimary   = "#7AAA77"
	HexSecondary = "#ADCFA3"
	HexAccent    = "#99C693"
	HexInfo      = "#7FA7C8"
	HexPass      = "#7AAA77"
	HexWarn      = "#D9B654"
	HexFail      = "#D77E6C"
	HexError     = "#D77E6C"
	HexMuted     = "#6F767C"
	HexText      = "#E6E8E6"
	HexTextDim   = "#7E8784"
	HexBgDark    = "#1A1D1C"
	HexBgCard    = "#242826"
	HexBgCode    = "#2A2A2A"
	HexBorder    = "#3A3F3C"

	// Visibility (dark terminal optimized)
	HexPublic  = "#2DD4BF" // teal-400 (ox-public-400)
	HexPrivate = "#FBBF24" // amber-400 (ox-warn-400)
)

// Hex color constants (light terminal/theme optimized)
const (
	HexLightPrimary   = "#3D643B"
	HexLightSecondary = "#324F31"
	HexLightAccent    = "#4E7D4C"
	HexLightInfo      = "#5580A0"
	HexLightPass      = "#3D643B"
	HexLightWarn      = "#A5842F"
	HexLightFail      = "#9F4838"
	HexLightError     = "#9F4838"
	HexLightMuted     = "#5A6066"
	HexLightText      = "#1A1A1A"
	HexLightTextDim   = "#5A6066"
	HexLightBgLight   = "#F8F8F8"
	HexLightBgCode    = "#F0F0F0"

	// Visibility (light terminal optimized)
	HexLightPublic  = "#0F766E" // teal-700 (ox-public-700)
	HexLightPrivate = "#B45309" // amber-700 (ox-warn-700)
)
