// Code generated by internal/session/cmd/gitleaks-port. DO NOT EDIT.
//
// Source: github.com/gitleaks/gitleaks @ v8.30.1 (config/gitleaks.toml)
// License (source): MIT
//
// Run `in internal/session/cmd/gitleaks-port:
//   go run . -in gitleaks-v8.30.1.toml -out ../../gitleaks_generated.go
//
// Or via the Makefile: make sync-gitleaks-rules.
//
// Rules whose regex doesn't compile under Go's regexp/RE2 engine are
// skipped (rare; logged at generation time). Rules duplicated by ox's
// hand-ported detectors (see gitleaks_detectors.go and secrets.go) are
// also skipped — the hand-ported versions carry class-specific
// [REDACTED_*] slugs that downstream consumers grep for.

package session

import "regexp"

// generatedGitleaksDetectors returns the auto-translated subset of the
// gitleaks default rule catalog. Combined with DefaultExtraDetectors,
// these provide ox's third-layer detection in RawWriter.
func generatedGitleaksDetectors() []SecretPattern {
	return []SecretPattern{
		{
			Name:    "1password_secret_key",
			Pattern: regexp.MustCompile(`\bA3-[A-Z0-9]{6}-(?:(?:[A-Z0-9]{11})|(?:[A-Z0-9]{6}-[A-Z0-9]{5}))-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}\b`),
			Redact:  "[REDACTED_1PASSWORD_SECRET_KEY]",
		},
		{
			Name:    "1password_service_account_token",
			Pattern: regexp.MustCompile(`ops_eyJ[a-zA-Z0-9+/]{250,}={0,3}`),
			Redact:  "[REDACTED_1PASSWORD_SERVICE_ACCOUNT_TOKEN]",
		},
		{
			Name:    "adafruit_api_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:adafruit)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9_-]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_ADAFRUIT_API_KEY]",
		},
		{
			Name:    "adobe_client_id",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:adobe)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-f0-9]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_ADOBE_CLIENT_ID]",
		},
		{
			Name:    "adobe_client_secret",
			Pattern: regexp.MustCompile(`\b(p8e-(?i)[a-z0-9]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_ADOBE_CLIENT_SECRET]",
		},
		{
			Name:    "age_secret_key",
			Pattern: regexp.MustCompile(`AGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58}`),
			Redact:  "[REDACTED_AGE_SECRET_KEY]",
		},
		{
			Name:    "airtable_personnal_access_token",
			Pattern: regexp.MustCompile(`\b(pat[[:alnum:]]{14}\.[a-f0-9]{64})\b`),
			Redact:  "[REDACTED_AIRTABLE_PERSONNAL_ACCESS_TOKEN]",
		},
		{
			Name:    "algolia_api_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:algolia)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_ALGOLIA_API_KEY]",
		},
		{
			Name:    "alibaba_access_key_id",
			Pattern: regexp.MustCompile(`\b(LTAI(?i)[a-z0-9]{20})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_ALIBABA_ACCESS_KEY_ID]",
		},
		{
			Name:    "alibaba_secret_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:alibaba)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{30})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_ALIBABA_SECRET_KEY]",
		},
		{
			Name:    "anthropic_admin_api_key",
			Pattern: regexp.MustCompile(`\b(sk-ant-admin01-[a-zA-Z0-9_\-]{93}AA)(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_ANTHROPIC_ADMIN_API_KEY]",
		},
		{
			Name:    "artifactory_api_key",
			Pattern: regexp.MustCompile(`\bAKCp[A-Za-z0-9]{69}\b`),
			Redact:  "[REDACTED_ARTIFACTORY_API_KEY]",
		},
		{
			Name:    "artifactory_reference_token",
			Pattern: regexp.MustCompile(`\bcmVmd[A-Za-z0-9]{59}\b`),
			Redact:  "[REDACTED_ARTIFACTORY_REFERENCE_TOKEN]",
		},
		{
			Name:    "asana_client_id",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:asana)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([0-9]{16})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_ASANA_CLIENT_ID]",
		},
		{
			Name:    "asana_client_secret",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:asana)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_ASANA_CLIENT_SECRET]",
		},
		{
			Name:    "atlassian_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:(?-i:ATLASSIAN|[Aa]tlassian)|(?-i:CONFLUENCE|[Cc]onfluence)|(?-i:JIRA|[Jj]ira))(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{20}[a-f0-9]{4})(?:[\x60'"\s;]|\\[nr]|$)|\b(ATATT3[A-Za-z0-9_\-=]{186})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_ATLASSIAN_API_TOKEN]",
		},
		{
			Name:    "authress_service_client_access_key",
			Pattern: regexp.MustCompile(`\b((?:sc|ext|scauth|authress)_(?i)[a-z0-9]{5,30}\.[a-z0-9]{4,6}\.(?-i:acc)[_-][a-z0-9-]{10,32}\.[a-z0-9+/_=-]{30,120})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_AUTHRESS_SERVICE_CLIENT_ACCESS_KEY]",
		},
		{
			Name:    "aws_amazon_bedrock_api_key_long_lived",
			Pattern: regexp.MustCompile(`\b(ABSK[A-Za-z0-9+/]{109,269}={0,2})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_AWS_AMAZON_BEDROCK_API_KEY_LONG_LIVED]",
		},
		{
			Name:    "aws_amazon_bedrock_api_key_short_lived",
			Pattern: regexp.MustCompile(`bedrock-api-key-YmVkcm9jay5hbWF6b25hd3MuY29t`),
			Redact:  "[REDACTED_AWS_AMAZON_BEDROCK_API_KEY_SHORT_LIVED]",
		},
		{
			Name:    "azure_ad_client_secret",
			Pattern: regexp.MustCompile(`(?:^|[\\'"\x60\s>=:(,)])([a-zA-Z0-9_~.]{3}\dQ~[a-zA-Z0-9_~.-]{31,34})(?:$|[\\'"\x60\s<),])`),
			Redact:  "[REDACTED_AZURE_AD_CLIENT_SECRET]",
		},
		{
			Name:    "beamer_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:beamer)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}(b_[a-z0-9=_\-]{44})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_BEAMER_API_TOKEN]",
		},
		{
			Name:    "bitbucket_client_id",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:bitbucket)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_BITBUCKET_CLIENT_ID]",
		},
		{
			Name:    "bitbucket_client_secret",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:bitbucket)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9=_\-]{64})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_BITBUCKET_CLIENT_SECRET]",
		},
		{
			Name:    "bittrex_access_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:bittrex)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_BITTREX_ACCESS_KEY]",
		},
		{
			Name:    "bittrex_secret_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:bittrex)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_BITTREX_SECRET_KEY]",
		},
		{
			Name:    "cisco_meraki_api_key",
			Pattern: regexp.MustCompile(`[\w.-]{0,50}?(?i:[\w.-]{0,50}?(?:(?-i:[Mm]eraki|MERAKI))(?:[ \t\w.-]{0,20})[\s'"]{0,3})(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([0-9a-f]{40})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_CISCO_MERAKI_API_KEY]",
		},
		{
			Name:    "clickhouse_cloud_api_secret_key",
			Pattern: regexp.MustCompile(`\b(4b1d[A-Za-z0-9]{38})\b`),
			Redact:  "[REDACTED_CLICKHOUSE_CLOUD_API_SECRET_KEY]",
		},
		{
			Name:    "clojars_api_token",
			Pattern: regexp.MustCompile(`(?i)CLOJARS_[a-z0-9]{60}`),
			Redact:  "[REDACTED_CLOJARS_API_TOKEN]",
		},
		{
			Name:    "codecov_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:codecov)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_CODECOV_ACCESS_TOKEN]",
		},
		{
			Name:    "cohere_api_token",
			Pattern: regexp.MustCompile(`[\w.-]{0,50}?(?i:[\w.-]{0,50}?(?:cohere|CO_API_KEY)(?:[ \t\w.-]{0,20})[\s'"]{0,3})(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-zA-Z0-9]{40})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_COHERE_API_TOKEN]",
		},
		{
			Name:    "coinbase_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:coinbase)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9_-]{64})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_COINBASE_ACCESS_TOKEN]",
		},
		{
			Name:    "confluent_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:confluent)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{16})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_CONFLUENT_ACCESS_TOKEN]",
		},
		{
			Name:    "confluent_secret_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:confluent)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{64})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_CONFLUENT_SECRET_KEY]",
		},
		{
			Name:    "contentful_delivery_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:contentful)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9=_\-]{43})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_CONTENTFUL_DELIVERY_API_TOKEN]",
		},
		{
			Name:    "curl_auth_header",
			Pattern: regexp.MustCompile(`\bcurl\b(?:.*?|.*?(?:[\r\n]{1,2}.*?){1,5})[ \t\n\r](?:-H|--header)(?:=|[ \t]{0,5})(?:"(?i)(?:Authorization:[ \t]{0,5}(?:Basic[ \t]([a-z0-9+/]{8,}={0,3})|(?:Bearer|(?:Api-)?Token)[ \t]([\w=~@.+/-]{8,})|([\w=~@.+/-]{8,}))|(?:(?:X-(?:[a-z]+-)?)?(?:Api-?)?(?:Key|Token)):[ \t]{0,5}([\w=~@.+/-]{8,}))"|'(?i)(?:Authorization:[ \t]{0,5}(?:Basic[ \t]([a-z0-9+/]{8,}={0,3})|(?:Bearer|(?:Api-)?Token)[ \t]([\w=~@.+/-]{8,})|([\w=~@.+/-]{8,}))|(?:(?:X-(?:[a-z]+-)?)?(?:Api-?)?(?:Key|Token)):[ \t]{0,5}([\w=~@.+/-]{8,}))')(?:\B|\s|\z)`),
			Redact:  "[REDACTED_CURL_AUTH_HEADER]",
		},
		{
			Name:    "curl_auth_user",
			Pattern: regexp.MustCompile(`\bcurl\b(?:.*|.*(?:[\r\n]{1,2}.*){1,5})[ \t\n\r](?:-u|--user)(?:=|[ \t]{0,5})("(:[^"]{3,}|[^:"]{3,}:|[^:"]{3,}:[^"]{3,})"|'([^:']{3,}:[^']{3,})'|((?:"[^"]{3,}"|'[^']{3,}'|[\w$@.-]+):(?:"[^"]{3,}"|'[^']{3,}'|[\w${}@.-]+)))(?:\s|\z)`),
			Redact:  "[REDACTED_CURL_AUTH_USER]",
		},
		{
			Name:    "databricks_api_token",
			Pattern: regexp.MustCompile(`\b(dapi[a-f0-9]{32}(?:-\d)?)(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_DATABRICKS_API_TOKEN]",
		},
		{
			Name:    "defined_networking_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:dnkey)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}(dnkey-[a-z0-9=_\-]{26}-[a-z0-9=_\-]{52})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_DEFINED_NETWORKING_API_TOKEN]",
		},
		{
			Name:    "droneci_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:droneci)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_DRONECI_ACCESS_TOKEN]",
		},
		{
			Name:    "dropbox_long_lived_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:dropbox)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{11}(AAAAAAAAAA)[a-z0-9\-_=]{43})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_DROPBOX_LONG_LIVED_API_TOKEN]",
		},
		{
			Name:    "dropbox_short_lived_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:dropbox)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}(sl\.[a-z0-9\-=_]{135})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_DROPBOX_SHORT_LIVED_API_TOKEN]",
		},
		{
			Name:    "duffel_api_token",
			Pattern: regexp.MustCompile(`duffel_(?:test|live)_(?i)[a-z0-9_\-=]{43}`),
			Redact:  "[REDACTED_DUFFEL_API_TOKEN]",
		},
		{
			Name:    "easypost_api_token",
			Pattern: regexp.MustCompile(`\bEZAK(?i)[a-z0-9]{54}\b`),
			Redact:  "[REDACTED_EASYPOST_API_TOKEN]",
		},
		{
			Name:    "easypost_test_api_token",
			Pattern: regexp.MustCompile(`\bEZTK(?i)[a-z0-9]{54}\b`),
			Redact:  "[REDACTED_EASYPOST_TEST_API_TOKEN]",
		},
		{
			Name:    "etsy_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:(?-i:ETSY|[Ee]tsy))(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{24})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_ETSY_ACCESS_TOKEN]",
		},
		{
			Name:    "facebook_page_access_token",
			Pattern: regexp.MustCompile(`\b(EAA[MC](?i)[a-z0-9]{100,})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_FACEBOOK_PAGE_ACCESS_TOKEN]",
		},
		{
			Name:    "fastly_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:fastly)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9=_\-]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_FASTLY_API_TOKEN]",
		},
		{
			Name:    "finicity_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:finicity)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-f0-9]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_FINICITY_API_TOKEN]",
		},
		{
			Name:    "finicity_client_secret",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:finicity)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{20})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_FINICITY_CLIENT_SECRET]",
		},
		{
			Name:    "finnhub_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:finnhub)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{20})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_FINNHUB_ACCESS_TOKEN]",
		},
		{
			Name:    "flickr_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:flickr)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_FLICKR_ACCESS_TOKEN]",
		},
		{
			Name:    "flutterwave_encryption_key",
			Pattern: regexp.MustCompile(`FLWSECK_TEST-(?i)[a-h0-9]{12}`),
			Redact:  "[REDACTED_FLUTTERWAVE_ENCRYPTION_KEY]",
		},
		{
			Name:    "flutterwave_public_key",
			Pattern: regexp.MustCompile(`FLWPUBK_TEST-(?i)[a-h0-9]{32}-X`),
			Redact:  "[REDACTED_FLUTTERWAVE_PUBLIC_KEY]",
		},
		{
			Name:    "flutterwave_secret_key",
			Pattern: regexp.MustCompile(`FLWSECK_TEST-(?i)[a-h0-9]{32}-X`),
			Redact:  "[REDACTED_FLUTTERWAVE_SECRET_KEY]",
		},
		{
			Name:    "flyio_access_token",
			Pattern: regexp.MustCompile(`\b((?:fo1_[\w-]{43}|fm1[ar]_[a-zA-Z0-9+\/]{100,}={0,3}|fm2_[a-zA-Z0-9+\/]{100,}={0,3}))(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_FLYIO_ACCESS_TOKEN]",
		},
		{
			Name:    "frameio_api_token",
			Pattern: regexp.MustCompile(`fio-u-(?i)[a-z0-9\-_=]{64}`),
			Redact:  "[REDACTED_FRAMEIO_API_TOKEN]",
		},
		{
			Name:    "freemius_secret_key",
			Pattern: regexp.MustCompile(`(?i)["']secret_key["']\s*=>\s*["'](sk_[\S]{29})["']`),
			Redact:  "[REDACTED_FREEMIUS_SECRET_KEY]",
		},
		{
			Name:    "freshbooks_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:freshbooks)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{64})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_FRESHBOOKS_ACCESS_TOKEN]",
		},
		{
			Name:    "gitlab_cicd_job_token",
			Pattern: regexp.MustCompile(`glcbt-[0-9a-zA-Z]{1,5}_[0-9a-zA-Z_-]{20}`),
			Redact:  "[REDACTED_GITLAB_CICD_JOB_TOKEN]",
		},
		{
			Name:    "gitlab_feature_flag_client_token",
			Pattern: regexp.MustCompile(`glffct-[0-9a-zA-Z_\-]{20}`),
			Redact:  "[REDACTED_GITLAB_FEATURE_FLAG_CLIENT_TOKEN]",
		},
		{
			Name:    "gitlab_incoming_mail_token",
			Pattern: regexp.MustCompile(`glimt-[0-9a-zA-Z_\-]{25}`),
			Redact:  "[REDACTED_GITLAB_INCOMING_MAIL_TOKEN]",
		},
		{
			Name:    "gitlab_kubernetes_agent_token",
			Pattern: regexp.MustCompile(`glagent-[0-9a-zA-Z_\-]{50}`),
			Redact:  "[REDACTED_GITLAB_KUBERNETES_AGENT_TOKEN]",
		},
		{
			Name:    "gitlab_oauth_app_secret",
			Pattern: regexp.MustCompile(`gloas-[0-9a-zA-Z_\-]{64}`),
			Redact:  "[REDACTED_GITLAB_OAUTH_APP_SECRET]",
		},
		{
			Name:    "gitlab_pat_routable",
			Pattern: regexp.MustCompile(`\bglpat-[0-9a-zA-Z_-]{27,300}\.[0-9a-z]{2}[0-9a-z]{7}\b`),
			Redact:  "[REDACTED_GITLAB_PAT_ROUTABLE]",
		},
		{
			Name:    "gitlab_ptt",
			Pattern: regexp.MustCompile(`glptt-[0-9a-f]{40}`),
			Redact:  "[REDACTED_GITLAB_PTT]",
		},
		{
			Name:    "gitlab_rrt",
			Pattern: regexp.MustCompile(`GR1348941[\w-]{20}`),
			Redact:  "[REDACTED_GITLAB_RRT]",
		},
		{
			Name:    "gitlab_runner_authentication_token",
			Pattern: regexp.MustCompile(`glrt-[0-9a-zA-Z_\-]{20}`),
			Redact:  "[REDACTED_GITLAB_RUNNER_AUTHENTICATION_TOKEN]",
		},
		{
			Name:    "gitlab_runner_authentication_token_routable",
			Pattern: regexp.MustCompile(`\bglrt-t\d_[0-9a-zA-Z_\-]{27,300}\.[0-9a-z]{2}[0-9a-z]{7}\b`),
			Redact:  "[REDACTED_GITLAB_RUNNER_AUTHENTICATION_TOKEN_ROUTABLE]",
		},
		{
			Name:    "gitlab_scim_token",
			Pattern: regexp.MustCompile(`glsoat-[0-9a-zA-Z_\-]{20}`),
			Redact:  "[REDACTED_GITLAB_SCIM_TOKEN]",
		},
		{
			Name:    "gitlab_session_cookie",
			Pattern: regexp.MustCompile(`_gitlab_session=[0-9a-z]{32}`),
			Redact:  "[REDACTED_GITLAB_SESSION_COOKIE]",
		},
		{
			Name:    "gitter_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:gitter)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9_-]{40})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_GITTER_ACCESS_TOKEN]",
		},
		{
			Name:    "gocardless_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:gocardless)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}(live_(?i)[a-z0-9\-_=]{40})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_GOCARDLESS_API_TOKEN]",
		},
		{
			Name:    "grafana_api_key",
			Pattern: regexp.MustCompile(`(?i)\b(eyJrIjoi[A-Za-z0-9]{70,400}={0,3})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_GRAFANA_API_KEY]",
		},
		{
			Name:    "harness_api_key",
			Pattern: regexp.MustCompile(`(?:pat|sat)\.[a-zA-Z0-9_-]{22}\.[a-zA-Z0-9]{24}\.[a-zA-Z0-9]{20}`),
			Redact:  "[REDACTED_HARNESS_API_KEY]",
		},
		{
			Name:    "hashicorp_tf_password",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:administrator_login_password|password)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}("[a-z0-9=_\-]{8,20}")(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_HASHICORP_TF_PASSWORD]",
		},
		{
			Name:    "heroku_api_key_v2",
			Pattern: regexp.MustCompile(`\b((HRKU-AA[0-9a-zA-Z_-]{58}))(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_HEROKU_API_KEY_V2]",
		},
		{
			Name:    "hubspot_api_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:hubspot)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_HUBSPOT_API_KEY]",
		},
		{
			Name:    "huggingface_access_token",
			Pattern: regexp.MustCompile(`\b(hf_(?i:[a-z]{34}))(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_HUGGINGFACE_ACCESS_TOKEN]",
		},
		{
			Name:    "huggingface_organization_api_token",
			Pattern: regexp.MustCompile(`\b(api_org_(?i:[a-z]{34}))(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_HUGGINGFACE_ORGANIZATION_API_TOKEN]",
		},
		{
			Name:    "infracost_api_token",
			Pattern: regexp.MustCompile(`\b(ico-[a-zA-Z0-9]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_INFRACOST_API_TOKEN]",
		},
		{
			Name:    "intercom_api_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:intercom)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9=_\-]{60})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_INTERCOM_API_KEY]",
		},
		{
			Name:    "intra42_client_secret",
			Pattern: regexp.MustCompile(`\b(s-s4t2(?:ud|af)-(?i)[abcdef0123456789]{64})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_INTRA42_CLIENT_SECRET]",
		},
		{
			Name:    "jfrog_api_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:jfrog|artifactory|bintray|xray)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{73})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_JFROG_API_KEY]",
		},
		{
			Name:    "jfrog_identity_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:jfrog|artifactory|bintray|xray)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{64})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_JFROG_IDENTITY_TOKEN]",
		},
		{
			Name:    "kraken_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:kraken)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9\/=_\+\-]{80,90})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_KRAKEN_ACCESS_TOKEN]",
		},
		{
			Name:    "kubernetes_secret_yaml",
			Pattern: regexp.MustCompile(`(?i)(?:\bkind:[ \t]*["']?\bsecret\b["']?(?s:.){0,200}?\bdata:(?s:.){0,100}?\s+([\w.-]+:(?:[ \t]*(?:\||>[-+]?)\s+)?[ \t]*(?:["']?[a-z0-9+/]{10,}={0,3}["']?|\{\{[ \t\w"|$:=,.-]+}}|""|''))|\bdata:(?s:.){0,100}?\s+([\w.-]+:(?:[ \t]*(?:\||>[-+]?)\s+)?[ \t]*(?:["']?[a-z0-9+/]{10,}={0,3}["']?|\{\{[ \t\w"|$:=,.-]+}}|""|''))(?s:.){0,200}?\bkind:[ \t]*["']?\bsecret\b["']?)`),
			Redact:  "[REDACTED_KUBERNETES_SECRET_YAML]",
		},
		{
			Name:    "kucoin_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:kucoin)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-f0-9]{24})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_KUCOIN_ACCESS_TOKEN]",
		},
		{
			Name:    "kucoin_secret_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:kucoin)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_KUCOIN_SECRET_KEY]",
		},
		{
			Name:    "launchdarkly_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:launchdarkly)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9=_\-]{40})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_LAUNCHDARKLY_ACCESS_TOKEN]",
		},
		{
			Name:    "linkedin_client_id",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:linked[_-]?in)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{14})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_LINKEDIN_CLIENT_ID]",
		},
		{
			Name:    "linkedin_client_secret",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:linked[_-]?in)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{16})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_LINKEDIN_CLIENT_SECRET]",
		},
		{
			Name:    "lob_api_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:lob)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}((live|test)_[a-f0-9]{35})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_LOB_API_KEY]",
		},
		{
			Name:    "lob_pub_api_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:lob)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}((test|live)_pub_[a-f0-9]{31})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_LOB_PUB_API_KEY]",
		},
		{
			Name:    "looker_client_id",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:looker)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{20})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_LOOKER_CLIENT_ID]",
		},
		{
			Name:    "looker_client_secret",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:looker)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{24})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_LOOKER_CLIENT_SECRET]",
		},
		{
			Name:    "mapbox_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:mapbox)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}(pk\.[a-z0-9]{60}\.[a-z0-9]{22})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_MAPBOX_API_TOKEN]",
		},
		{
			Name:    "mattermost_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:mattermost)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{26})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_MATTERMOST_ACCESS_TOKEN]",
		},
		{
			Name:    "maxmind_license_key",
			Pattern: regexp.MustCompile(`\b([A-Za-z0-9]{6}_[A-Za-z0-9]{29}_mmk)(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_MAXMIND_LICENSE_KEY]",
		},
		{
			Name:    "messagebird_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:message[_-]?bird)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{25})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_MESSAGEBIRD_API_TOKEN]",
		},
		{
			Name:    "messagebird_client_id",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:message[_-]?bird)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_MESSAGEBIRD_CLIENT_ID]",
		},
		{
			Name:    "microsoft_teams_webhook",
			Pattern: regexp.MustCompile(`https://[a-z0-9]+\.webhook\.office\.com/webhookb2/[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}@[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}/IncomingWebhook/[a-z0-9]{32}/[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}`),
			Redact:  "[REDACTED_MICROSOFT_TEAMS_WEBHOOK]",
		},
		{
			Name:    "new_relic_browser_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}(NRJS-[a-f0-9]{19})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_NEW_RELIC_BROWSER_API_TOKEN]",
		},
		{
			Name:    "new_relic_insert_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}(NRII-[a-z0-9-]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_NEW_RELIC_INSERT_KEY]",
		},
		{
			Name:    "new_relic_user_api_id",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{64})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_NEW_RELIC_USER_API_ID]",
		},
		{
			Name:    "notion_api_token",
			Pattern: regexp.MustCompile(`\b(ntn_[0-9]{11}[A-Za-z0-9]{32}[A-Za-z0-9]{3})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_NOTION_API_TOKEN]",
		},
		{
			Name:    "nuget_config_password",
			Pattern: regexp.MustCompile(`(?i)<add key=\"(?:(?:ClearText)?Password)\"\s*value=\"(.{8,})\"\s*/>`),
			Redact:  "[REDACTED_NUGET_CONFIG_PASSWORD]",
		},
		{
			Name:    "nytimes_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:nytimes|new-york-times,|newyorktimes)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9=_\-]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_NYTIMES_ACCESS_TOKEN]",
		},
		{
			Name:    "octopus_deploy_api_key",
			Pattern: regexp.MustCompile(`\b(API-[A-Z0-9]{26})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_OCTOPUS_DEPLOY_API_KEY]",
		},
		{
			Name:    "okta_access_token",
			Pattern: regexp.MustCompile(`[\w.-]{0,50}?(?i:[\w.-]{0,50}?(?:(?-i:[Oo]kta|OKTA))(?:[ \t\w.-]{0,20})[\s'"]{0,3})(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}(00[\w=\-]{40})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_OKTA_ACCESS_TOKEN]",
		},
		{
			Name:    "openshift_user_token",
			Pattern: regexp.MustCompile(`\b(sha256~[\w-]{43})(?:[^\w-]|\z)`),
			Redact:  "[REDACTED_OPENSHIFT_USER_TOKEN]",
		},
		{
			Name:    "perplexity_api_key",
			Pattern: regexp.MustCompile(`\b(pplx-[a-zA-Z0-9]{48})(?:[\x60'"\s;]|\\[nr]|$|\b)`),
			Redact:  "[REDACTED_PERPLEXITY_API_KEY]",
		},
		{
			Name:    "plaid_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:plaid)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}(access-(?:sandbox|development|production)-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_PLAID_API_TOKEN]",
		},
		{
			Name:    "plaid_client_id",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:plaid)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{24})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_PLAID_CLIENT_ID]",
		},
		{
			Name:    "plaid_secret_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:plaid)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{30})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_PLAID_SECRET_KEY]",
		},
		{
			Name:    "planetscale_oauth_token",
			Pattern: regexp.MustCompile(`\b(pscale_oauth_[\w=\.-]{32,64})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_PLANETSCALE_OAUTH_TOKEN]",
		},
		{
			Name:    "prefect_api_token",
			Pattern: regexp.MustCompile(`\b(pnu_[a-zA-Z0-9]{36})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_PREFECT_API_TOKEN]",
		},
		{
			Name:    "privateai_api_token",
			Pattern: regexp.MustCompile(`[\w.-]{0,50}?(?i:[\w.-]{0,50}?(?:private[_-]?ai)(?:[ \t\w.-]{0,20})[\s'"]{0,3})(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{32})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_PRIVATEAI_API_TOKEN]",
		},
		{
			Name:    "pulumi_api_token",
			Pattern: regexp.MustCompile(`\b(pul-[a-f0-9]{40})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_PULUMI_API_TOKEN]",
		},
		{
			Name:    "rapidapi_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:rapidapi)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9_-]{50})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_RAPIDAPI_ACCESS_TOKEN]",
		},
		{
			Name:    "readme_api_token",
			Pattern: regexp.MustCompile(`\b(rdme_[a-z0-9]{70})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_README_API_TOKEN]",
		},
		{
			Name:    "scalingo_api_token",
			Pattern: regexp.MustCompile(`\b(tk-us-[\w-]{48})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_SCALINGO_API_TOKEN]",
		},
		{
			Name:    "sendbird_access_id",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:sendbird)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_SENDBIRD_ACCESS_ID]",
		},
		{
			Name:    "sendbird_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:sendbird)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-f0-9]{40})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_SENDBIRD_ACCESS_TOKEN]",
		},
		{
			Name:    "settlemint_application_access_token",
			Pattern: regexp.MustCompile(`\b(sm_aat_[a-zA-Z0-9]{16})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_SETTLEMINT_APPLICATION_ACCESS_TOKEN]",
		},
		{
			Name:    "settlemint_personal_access_token",
			Pattern: regexp.MustCompile(`\b(sm_pat_[a-zA-Z0-9]{16})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_SETTLEMINT_PERSONAL_ACCESS_TOKEN]",
		},
		{
			Name:    "settlemint_service_access_token",
			Pattern: regexp.MustCompile(`\b(sm_sat_[a-zA-Z0-9]{16})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_SETTLEMINT_SERVICE_ACCESS_TOKEN]",
		},
		{
			Name:    "shippo_api_token",
			Pattern: regexp.MustCompile(`\b(shippo_(?:live|test)_[a-fA-F0-9]{40})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_SHIPPO_API_TOKEN]",
		},
		{
			Name:    "sidekiq_secret",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:BUNDLE_ENTERPRISE__CONTRIBSYS__COM|BUNDLE_GEMS__CONTRIBSYS__COM)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-f0-9]{8}:[a-f0-9]{8})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_SIDEKIQ_SECRET]",
		},
		{
			Name:    "sidekiq_sensitive_url",
			Pattern: regexp.MustCompile(`(?i)\bhttps?://([a-f0-9]{8}:[a-f0-9]{8})@(?:gems.contribsys.com|enterprise.contribsys.com)(?:[\/|\#|\?|:]|$)`),
			Redact:  "[REDACTED_SIDEKIQ_SENSITIVE_URL]",
		},
		{
			Name:    "sonar_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:sonar[_.-]?(login|token))(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}((?:squ_|sqp_|sqa_)?[a-z0-9=_\-]{40})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_SONAR_API_TOKEN]",
		},
		{
			Name:    "sourcegraph_access_token",
			Pattern: regexp.MustCompile(`(?i)\b(\b(sgp_(?:[a-fA-F0-9]{16}|local)_[a-fA-F0-9]{40}|sgp_[a-fA-F0-9]{40}|[a-fA-F0-9]{40})\b)(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_SOURCEGRAPH_ACCESS_TOKEN]",
		},
		{
			Name:    "squarespace_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:squarespace)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_SQUARESPACE_ACCESS_TOKEN]",
		},
		{
			Name:    "sumologic_access_id",
			Pattern: regexp.MustCompile(`[\w.-]{0,50}?(?i:[\w.-]{0,50}?(?:(?-i:[Ss]umo|SUMO))(?:[ \t\w.-]{0,20})[\s'"]{0,3})(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}(su[a-zA-Z0-9]{12})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_SUMOLOGIC_ACCESS_ID]",
		},
		{
			Name:    "sumologic_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:(?-i:[Ss]umo|SUMO))(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{64})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_SUMOLOGIC_ACCESS_TOKEN]",
		},
		{
			Name:    "telegram_bot_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:telegr)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([0-9]{5,16}:(?-i:A)[a-z0-9_\-]{34})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_TELEGRAM_BOT_API_TOKEN]",
		},
		{
			Name:    "travisci_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:travis)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{22})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_TRAVISCI_ACCESS_TOKEN]",
		},
		{
			Name:    "twitch_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:twitch)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{30})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_TWITCH_API_TOKEN]",
		},
		{
			Name:    "twitter_access_secret",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:twitter)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{45})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_TWITTER_ACCESS_SECRET]",
		},
		{
			Name:    "twitter_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:twitter)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([0-9]{15,25}-[a-zA-Z0-9]{20,40})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_TWITTER_ACCESS_TOKEN]",
		},
		{
			Name:    "twitter_api_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:twitter)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{25})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_TWITTER_API_KEY]",
		},
		{
			Name:    "twitter_api_secret",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:twitter)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{50})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_TWITTER_API_SECRET]",
		},
		{
			Name:    "twitter_bearer_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:twitter)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}(A{22}[a-zA-Z0-9%]{80,100})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_TWITTER_BEARER_TOKEN]",
		},
		{
			Name:    "typeform_api_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:typeform)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}(tfp_[a-z0-9\-_\.=]{59})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_TYPEFORM_API_TOKEN]",
		},
		{
			Name:    "yandex_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:yandex)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}(t1\.[A-Z0-9a-z_-]+[=]{0,2}\.[A-Z0-9a-z_-]{86}[=]{0,2})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_YANDEX_ACCESS_TOKEN]",
		},
		{
			Name:    "yandex_api_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:yandex)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}(AQVN[A-Za-z0-9_\-]{35,38})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_YANDEX_API_KEY]",
		},
		{
			Name:    "yandex_aws_access_token",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:yandex)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}(YC[a-zA-Z0-9_\-]{38})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_YANDEX_AWS_ACCESS_TOKEN]",
		},
		{
			Name:    "zendesk_secret_key",
			Pattern: regexp.MustCompile(`(?i)[\w.-]{0,50}?(?:zendesk)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}([a-z0-9]{40})(?:[\x60'"\s;]|\\[nr]|$)`),
			Redact:  "[REDACTED_ZENDESK_SECRET_KEY]",
		},
	}
}
