// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package whisperdb

import (
	"database/sql"
)

type Cursor struct {
	AgentID   string `json:"agent_id"`
	LastSeen  string `json:"last_seen"`
	UpdatedAt string `json:"updated_at"`
}

type RelayedMurmur struct {
	MurmurID  string `json:"murmur_id"`
	Scope     string `json:"scope"`
	RelayedAt string `json:"relayed_at"`
}

type Whisper struct {
	ID            string         `json:"id"`
	Scope         string         `json:"scope"`
	Type          string         `json:"type"`
	Source        string         `json:"source"`
	Topic         string         `json:"topic"`
	Content       string         `json:"content"`
	Importance    string         `json:"importance"`
	CreatedAt     string         `json:"created_at"`
	AgentID       sql.NullString `json:"agent_id"`
	PrincipalID   sql.NullString `json:"principal_id"`
	PrincipalType sql.NullString `json:"principal_type"`
	TeamID        sql.NullString `json:"team_id"`
	Metadata      sql.NullString `json:"metadata"`
}
