// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package whisperdb

import (
	"context"
	"database/sql"
)

const deleteAllRelayed = `-- name: DeleteAllRelayed :exec
DELETE FROM relayed_murmurs
`

func (q *Queries) DeleteAllRelayed(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllRelayed)
	return err
}

const deleteAllWhispers = `-- name: DeleteAllWhispers :exec
DELETE FROM whispers
`

func (q *Queries) DeleteAllWhispers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllWhispers)
	return err
}

const getCursor = `-- name: GetCursor :one
SELECT last_seen FROM cursors WHERE agent_id = ?
`

func (q *Queries) GetCursor(ctx context.Context, agentID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCursor, agentID)
	var last_seen string
	err := row.Scan(&last_seen)
	return last_seen, err
}

const insertWhisper = `-- name: InsertWhisper :exec
INSERT OR IGNORE INTO whispers
    (id, scope, type, source, topic, content, importance, created_at,
     agent_id, principal_id, principal_type, team_id, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertWhisperParams struct {
	ID            string         `json:"id"`
	Scope         string         `json:"scope"`
	Type          string         `json:"type"`
	Source        string         `json:"source"`
	Topic         string         `json:"topic"`
	Content       string         `json:"content"`
	Importance    string         `json:"importance"`
	CreatedAt     string         `json:"created_at"`
	AgentID       sql.NullString `json:"agent_id"`
	PrincipalID   sql.NullString `json:"principal_id"`
	PrincipalType sql.NullString `json:"principal_type"`
	TeamID        sql.NullString `json:"team_id"`
	Metadata      sql.NullString `json:"metadata"`
}

func (q *Queries) InsertWhisper(ctx context.Context, arg InsertWhisperParams) error {
	_, err := q.db.ExecContext(ctx, insertWhisper,
		arg.ID,
		arg.Scope,
		arg.Type,
		arg.Source,
		arg.Topic,
		arg.Content,
		arg.Importance,
		arg.CreatedAt,
		arg.AgentID,
		arg.PrincipalID,
		arg.PrincipalType,
		arg.TeamID,
		arg.Metadata,
	)
	return err
}

const isRelayed = `-- name: IsRelayed :one
SELECT COUNT(*) FROM relayed_murmurs WHERE murmur_id = ? AND scope = ?
`

type IsRelayedParams struct {
	MurmurID string `json:"murmur_id"`
	Scope    string `json:"scope"`
}

func (q *Queries) IsRelayed(ctx context.Context, arg IsRelayedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isRelayed, arg.MurmurID, arg.Scope)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markRelayed = `-- name: MarkRelayed :exec
INSERT OR IGNORE INTO relayed_murmurs (murmur_id, scope, relayed_at) VALUES (?, ?, ?)
`

type MarkRelayedParams struct {
	MurmurID  string `json:"murmur_id"`
	Scope     string `json:"scope"`
	RelayedAt string `json:"relayed_at"`
}

func (q *Queries) MarkRelayed(ctx context.Context, arg MarkRelayedParams) error {
	_, err := q.db.ExecContext(ctx, markRelayed, arg.MurmurID, arg.Scope, arg.RelayedAt)
	return err
}

const pruneCursors = `-- name: PruneCursors :execresult
DELETE FROM cursors WHERE updated_at < ?
`

func (q *Queries) PruneCursors(ctx context.Context, updatedAt string) (sql.Result, error) {
	return q.db.ExecContext(ctx, pruneCursors, updatedAt)
}

const pruneRelayed = `-- name: PruneRelayed :execresult
DELETE FROM relayed_murmurs WHERE relayed_at < ?
`

func (q *Queries) PruneRelayed(ctx context.Context, relayedAt string) (sql.Result, error) {
	return q.db.ExecContext(ctx, pruneRelayed, relayedAt)
}

const pruneWhispers = `-- name: PruneWhispers :execresult
DELETE FROM whispers WHERE created_at < ?
`

func (q *Queries) PruneWhispers(ctx context.Context, createdAt string) (sql.Result, error) {
	return q.db.ExecContext(ctx, pruneWhispers, createdAt)
}

const removeCursor = `-- name: RemoveCursor :exec
DELETE FROM cursors WHERE agent_id = ?
`

func (q *Queries) RemoveCursor(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, removeCursor, agentID)
	return err
}

const upsertCursor = `-- name: UpsertCursor :exec
INSERT INTO cursors (agent_id, last_seen, updated_at) VALUES (?, ?, ?)
ON CONFLICT(agent_id) DO UPDATE SET last_seen = excluded.last_seen, updated_at = excluded.updated_at
`

type UpsertCursorParams struct {
	AgentID   string `json:"agent_id"`
	LastSeen  string `json:"last_seen"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) UpsertCursor(ctx context.Context, arg UpsertCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertCursor, arg.AgentID, arg.LastSeen, arg.UpdatedAt)
	return err
}
