#!/usr/bin/env bash
# Publish ox CLI component catalog to sageox-design/catalog/cli/.
#
# Implements the contract at sageox-design/catalog/README.md:
#   • Single self-contained index.html (inline CSS, inline JS, fonts via CDN)
#   • No external asset dependencies
#   • Mode / Calm / Notes toggles + left-rail TOC
#   • Tokens mirrored from sageox-design/tokens/
#
# Usage:
#   SAGEOX_DESIGN_REPO=~/conductor/workspaces/sageox-design/bogota-v2 \
#       bash scripts/publish-design-catalog.sh
#
#   bash scripts/publish-design-catalog.sh --pr    # also open a PR
#
# Per-surface configuration — keep these four lines in sync with the
# contract (everything else is surface-agnostic boilerplate).
set -euo pipefail

SURFACE="cli"
BUILD_CMD=(make catalog-build)
BUILD_CWD_REL=".."
OUT_REL=".context/catalog-out/${SURFACE}"
# end per-surface config

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SAGEOX_DESIGN_REPO="${SAGEOX_DESIGN_REPO:-$HOME/conductor/workspaces/sageox-design/bogota-v2}"

if [ ! -d "$SAGEOX_DESIGN_REPO" ]; then
  echo "error: SAGEOX_DESIGN_REPO not found at $SAGEOX_DESIGN_REPO" >&2
  echo "       set SAGEOX_DESIGN_REPO=/path/to/sageox-design/checkout" >&2
  exit 1
fi

OPEN_PR=0
for arg in "$@"; do
  case "$arg" in
    --pr) OPEN_PR=1 ;;
    -h|--help)
      sed -n '2,18p' "$0"
      exit 0
      ;;
  esac
done

cd "$REPO_ROOT"
echo "→ Building catalog snapshot via: ${BUILD_CMD[*]}"
"${BUILD_CMD[@]}"

OUT_DIR="$REPO_ROOT/$OUT_REL"
if [ ! -f "$OUT_DIR/index.html" ]; then
  echo "error: build did not produce $OUT_DIR/index.html" >&2
  exit 1
fi

DEST_DIR="$SAGEOX_DESIGN_REPO/catalog/${SURFACE}"
echo "→ Syncing $OUT_DIR → $DEST_DIR"
mkdir -p "$DEST_DIR"
rsync -a --delete \
  --exclude '.git' \
  "$OUT_DIR/" "$DEST_DIR/"

# README per console convention — annotated, "do not hand-edit".
GEN_DATE="$(date -u +%Y-%m-%d)"
OX_VERSION="$(grep 'Version.*=' "$REPO_ROOT/internal/version/version.go" | head -1 | sed 's/.*"\(.*\)"/\1/')"
cat > "$DEST_DIR/README.md" <<EOF
# Catalog export · cli

Generated by [\`sageox/ox\` scripts/publish-design-catalog.sh](https://github.com/sageox/ox/tree/main/scripts/publish-design-catalog.sh) on ${GEN_DATE} from ox ${OX_VERSION}.
Do not edit \`index.html\` by hand — it will be overwritten on the next export.
Source of truth: \`internal/uicatalog/entries/\` in the [sageox/ox](https://github.com/sageox/ox) repo.

Asciinema \`.cast\` recordings and \`charmbracelet/freeze\` SVG snapshots are
inlined into the single \`index.html\` per the
[catalog contract](https://sageox-design.netlify.app/catalog/README.md).
EOF

echo "✓ Wrote $DEST_DIR/index.html and README.md"

if [ "$OPEN_PR" -eq 1 ]; then
  cd "$SAGEOX_DESIGN_REPO"
  BRANCH="ox-cli-catalog-${GEN_DATE}"
  git checkout -B "$BRANCH"
  git add "catalog/${SURFACE}/"
  if git diff --cached --quiet; then
    echo "→ no changes; skipping PR"
    exit 0
  fi
  git commit -m "catalog(cli): refresh ox ${OX_VERSION} snapshot"
  git push -u origin "$BRANCH"
  gh pr create --fill --base main --head "$BRANCH" || true
fi
