package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestIsAgentSupported(t *testing.T) {
	tests := []struct {
		name      string
		agentType string
		want      bool
	}{
		{
			name:      "claude slug is supported",
			agentType: "claude",
			want:      true,
		},
		{
			name:      "claude-code alias is supported",
			agentType: "claude-code",
			want:      true,
		},
		{
			name:      "codex is supported",
			agentType: "codex",
			want:      true,
		},
		{
			name:      "cursor is not supported",
			agentType: "cursor",
			want:      false,
		},
		{
			name:      "windsurf is not supported",
			agentType: "windsurf",
			want:      false,
		},
		{
			name:      "droid is not supported",
			agentType: "droid",
			want:      false,
		},
		{
			name:      "empty agent type is not supported",
			agentType: "",
			want:      false,
		},
		{
			name:      "unknown agent is not supported",
			agentType: "unknown-agent",
			want:      false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := isAgentSupported(tt.agentType)
			if got != tt.want {
				t.Errorf("isAgentSupported(%q) = %v, want %v", tt.agentType, got, tt.want)
			}
		})
	}
}

func TestGetAgentSupportNotice(t *testing.T) {
	tests := []struct {
		name         string
		agentType    string
		wantEmpty    bool
		wantContains string
	}{
		{
			name:      "claude returns empty notice",
			agentType: "claude",
			wantEmpty: true,
		},
		{
			name:      "claude-code alias returns empty notice",
			agentType: "claude-code",
			wantEmpty: true,
		},
		{
			name:      "codex returns empty notice",
			agentType: "codex",
			wantEmpty: true,
		},
		{
			name:         "cursor returns notice with display name",
			agentType:    "cursor",
			wantEmpty:    false,
			wantContains: "Cursor",
		},
		{
			name:         "empty agent returns notice about this agent",
			agentType:    "",
			wantEmpty:    false,
			wantContains: "this agent",
		},
		{
			name:         "windsurf returns notice with display name",
			agentType:    "windsurf",
			wantEmpty:    false,
			wantContains: "Windsurf",
		},
		{
			name:         "unsupported agent notice explains review needed",
			agentType:    "cursor",
			wantEmpty:    false,
			wantContains: "review plans deeply",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := getAgentSupportNotice(tt.agentType)

			if tt.wantEmpty && got != "" {
				t.Errorf("getAgentSupportNotice(%q) = %q, want empty", tt.agentType, got)
			}

			if !tt.wantEmpty && got == "" {
				t.Errorf("getAgentSupportNotice(%q) = empty, want non-empty", tt.agentType)
			}

			if tt.wantContains != "" && !strings.Contains(got, tt.wantContains) {
				t.Errorf("getAgentSupportNotice(%q) = %q, want to contain %q", tt.agentType, got, tt.wantContains)
			}
		})
	}
}

func TestLoadTeamInstructions(t *testing.T) {
	tests := []struct {
		name      string
		files     map[string]string // filename -> content
		teamName  string
		wantNil   bool
		wantFiles []string
		wantIn    string // substring expected in content
	}{
		{
			name:    "empty dir returns nil",
			files:   map[string]string{},
			wantNil: true,
		},
		{
			name: "auto-generated AGENTS.md is skipped",
			files: map[string]string{
				"AGENTS.md": "# SageOx\n\n---\n*Generated by SageOx CLI v0.17.0 at 2026-01-01T00:00:00Z*\n",
			},
			wantNil: true,
		},
		{
			name: "real AGENTS.md is loaded",
			files: map[string]string{
				"AGENTS.md": "# Team Instructions\n\nUse Go for everything.\n",
			},
			teamName:  "TestTeam",
			wantFiles: []string{"AGENTS.md"},
			wantIn:    "Use Go for everything",
		},
		{
			name: "CLAUDE.md only is loaded",
			files: map[string]string{
				"CLAUDE.md": "# Claude Config\n\nPrefer simplicity.\n",
			},
			teamName:  "TestTeam",
			wantFiles: []string{"CLAUDE.md"},
			wantIn:    "Prefer simplicity",
		},
		{
			name: "both files are concatenated",
			files: map[string]string{
				"AGENTS.md": "# Agent Instructions\n\nRule one.\n",
				"CLAUDE.md": "# Claude Config\n\nRule two.\n",
			},
			teamName:  "TestTeam",
			wantFiles: []string{"AGENTS.md", "CLAUDE.md"},
			wantIn:    "Rule one",
		},
		{
			name: "boilerplate AGENTS.md plus real CLAUDE.md returns only CLAUDE.md",
			files: map[string]string{
				"AGENTS.md": "# SageOx\n\n---\n*Generated by SageOx CLI v0.17.0*\n",
				"CLAUDE.md": "# Claude Config\n\nReal instructions.\n",
			},
			teamName:  "TestTeam",
			wantFiles: []string{"CLAUDE.md"},
			wantIn:    "Real instructions",
		},
		{
			name:    "empty path returns nil",
			files:   nil,
			wantNil: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// handle empty path case
			if tt.files == nil {
				got := loadTeamInstructions("", tt.teamName)
				if got != nil {
					t.Fatalf("loadTeamInstructions(\"\", ...) = non-nil, want nil")
				}
				return
			}

			dir := t.TempDir()
			for name, content := range tt.files {
				if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0644); err != nil {
					t.Fatalf("write %s: %v", name, err)
				}
			}

			got := loadTeamInstructions(dir, tt.teamName)

			if tt.wantNil {
				if got != nil {
					t.Fatalf("want nil, got %+v", got)
				}
				return
			}

			if got == nil {
				t.Fatal("want non-nil, got nil")
			}

			if got.TeamName != tt.teamName {
				t.Errorf("team_name = %q, want %q", got.TeamName, tt.teamName)
			}

			if len(got.Files) != len(tt.wantFiles) {
				t.Errorf("files = %v, want %v", got.Files, tt.wantFiles)
			} else {
				for i, f := range tt.wantFiles {
					if got.Files[i] != f {
						t.Errorf("files[%d] = %q, want %q", i, got.Files[i], f)
					}
				}
			}

			if tt.wantIn != "" && !strings.Contains(got.Content, tt.wantIn) {
				t.Errorf("content missing %q, got: %s", tt.wantIn, got.Content)
			}

			if got.Size != len(got.Content) {
				t.Errorf("size = %d, want %d (len of content)", got.Size, len(got.Content))
			}

			if got.Tokens == 0 {
				t.Error("tokens = 0, want > 0")
			}
		})
	}
}

func TestIsAutoGeneratedAgentsMD(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{
			name:    "auto-generated with version",
			content: "# SageOx\n\n---\n*Generated by SageOx CLI v0.17.0 at 2026-01-01*\n",
			want:    true,
		},
		{
			name:    "real team instructions",
			content: "# Team Instructions\n\nUse Go.\n",
			want:    false,
		},
		{
			name:    "empty content",
			content: "",
			want:    false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isAutoGeneratedAgentsMD(tt.content); got != tt.want {
				t.Errorf("isAutoGeneratedAgentsMD() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestCanonicalAgentType(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want string
	}{
		{name: "empty", in: "", want: ""},
		{name: "codex", in: "codex", want: "codex"},
		{name: "claude-code alias", in: "claude-code", want: "claude"},
		{name: "claude display", in: "Claude Code", want: "claude"},
		{name: "cursor display", in: "Cursor", want: "cursor"},
		{name: "already slug", in: "cursor", want: "cursor"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := canonicalAgentType(tt.in)
			if got != tt.want {
				t.Errorf("canonicalAgentType(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestCodexLifecycleNotification(t *testing.T) {
	tests := []struct {
		name      string
		agentType string
		wantEmpty bool
	}{
		{name: "codex", agentType: "codex", wantEmpty: false},
		{name: "codex display alias", agentType: "Codex", wantEmpty: false},
		{name: "claude", agentType: "claude", wantEmpty: true},
		{name: "empty", agentType: "", wantEmpty: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := codexLifecycleNotification(tt.agentType)
			if tt.wantEmpty && got != "" {
				t.Fatalf("codexLifecycleNotification(%q) = %q, want empty", tt.agentType, got)
			}
			if !tt.wantEmpty {
				if got == "" {
					t.Fatalf("codexLifecycleNotification(%q) = empty, want non-empty", tt.agentType)
				}
				if !strings.Contains(got, "no native hooks") {
					t.Errorf("expected Codex lifecycle note to mention no hooks, got: %q", got)
				}
				if !strings.Contains(got, "ox agent <id> session start") {
					t.Errorf("expected Codex lifecycle note to mention manual session start, got: %q", got)
				}
			}
		})
	}
}
