package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"
)

func TestIsAutoGeneratedAgentsMD_Coverage(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{
			name:    "auto-generated boilerplate",
			content: "# Agents\n\n*Generated by SageOx CLI* - do not edit\n\nSome content",
			want:    true,
		},
		{
			name:    "hand-authored content",
			content: "# Team Conventions\n\nUse Go 1.21 or later.\n",
			want:    false,
		},
		{
			name:    "empty content",
			content: "",
			want:    false,
		},
		{
			name:    "partial match substring",
			content: "This mentions Generated by SageOx but is not the marker",
			want:    false,
		},
		{
			name:    "exact marker with asterisk",
			content: "*Generated by SageOx CLI",
			want:    true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got := isAutoGeneratedAgentsMD(tt.content)
			if got != tt.want {
				t.Errorf("isAutoGeneratedAgentsMD(%q) = %v, want %v", tt.content, got, tt.want)
			}
		})
	}
}

func TestLoadTeamInstructions_EmptyPath(t *testing.T) {
	t.Parallel()
	got := loadTeamInstructions("", "my-team")
	if got != nil {
		t.Error("expected nil for empty path")
	}
}

func TestLoadTeamInstructions_NoFiles(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	got := loadTeamInstructions(dir, "my-team")
	if got != nil {
		t.Error("expected nil when no instruction files exist")
	}
}

func TestLoadTeamInstructions_OnlyAutoGenerated(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	// write auto-generated AGENTS.md
	if err := os.WriteFile(filepath.Join(dir, "AGENTS.md"), []byte("*Generated by SageOx CLI*\nauto content"), 0644); err != nil {
		t.Fatal(err)
	}
	got := loadTeamInstructions(dir, "my-team")
	if got != nil {
		t.Error("expected nil when AGENTS.md is auto-generated and no CLAUDE.md exists")
	}
}

func TestLoadTeamInstructions_ClaudeMDOnly(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	content := "# Claude Instructions\n\nUse Go conventions."
	if err := os.WriteFile(filepath.Join(dir, "CLAUDE.md"), []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	got := loadTeamInstructions(dir, "test-team")
	if got == nil {
		t.Fatal("expected non-nil result")
	}
	if got.Source != "CLAUDE.md" {
		t.Errorf("Source = %q, want %q", got.Source, "CLAUDE.md")
	}
	if got.TeamName != "test-team" {
		t.Errorf("TeamName = %q, want %q", got.TeamName, "test-team")
	}
	if got.Content != content {
		t.Errorf("Content mismatch")
	}
	if len(got.Files) != 1 || got.Files[0] != "CLAUDE.md" {
		t.Errorf("Files = %v, want [CLAUDE.md]", got.Files)
	}
}

func TestLoadTeamInstructions_BothFiles(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	agentsContent := "# Team AGENTS.md\nHand-authored."
	claudeContent := "# Claude specific"

	if err := os.WriteFile(filepath.Join(dir, "AGENTS.md"), []byte(agentsContent), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "CLAUDE.md"), []byte(claudeContent), 0644); err != nil {
		t.Fatal(err)
	}

	got := loadTeamInstructions(dir, "dual-team")
	if got == nil {
		t.Fatal("expected non-nil result")
	}
	if got.Source != "AGENTS.md + CLAUDE.md" {
		t.Errorf("Source = %q, want %q", got.Source, "AGENTS.md + CLAUDE.md")
	}
	if len(got.Files) != 2 {
		t.Errorf("Files length = %d, want 2", len(got.Files))
	}
}

func TestDiscoverMemoryFiles(t *testing.T) {
	t.Parallel()

	t.Run("nonexistent directory", func(t *testing.T) {
		t.Parallel()
		files := discoverMemoryFiles("/nonexistent/path")
		if files != nil {
			t.Errorf("expected nil for nonexistent dir, got %v", files)
		}
	})

	t.Run("empty directory", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()
		files := discoverMemoryFiles(dir)
		if files != nil {
			t.Errorf("expected nil for empty dir, got %v", files)
		}
	})

	t.Run("only non-md files", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()
		os.WriteFile(filepath.Join(dir, "notes.txt"), []byte("text"), 0644)
		os.WriteFile(filepath.Join(dir, "data.json"), []byte("{}"), 0644)
		files := discoverMemoryFiles(dir)
		if files != nil {
			t.Errorf("expected nil when no .md files, got %v", files)
		}
	})

	t.Run("md files sorted reverse chronologically", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()
		os.WriteFile(filepath.Join(dir, "2024-01-01.md"), []byte("jan"), 0644)
		os.WriteFile(filepath.Join(dir, "2024-03-15.md"), []byte("mar"), 0644)
		os.WriteFile(filepath.Join(dir, "2024-02-10.md"), []byte("feb"), 0644)

		files := discoverMemoryFiles(dir)
		if len(files) != 3 {
			t.Fatalf("expected 3 files, got %d", len(files))
		}
		// reverse chronological: newest first
		if files[0] != "2024-03-15.md" {
			t.Errorf("files[0] = %q, want %q", files[0], "2024-03-15.md")
		}
		if files[1] != "2024-02-10.md" {
			t.Errorf("files[1] = %q, want %q", files[1], "2024-02-10.md")
		}
		if files[2] != "2024-01-01.md" {
			t.Errorf("files[2] = %q, want %q", files[2], "2024-01-01.md")
		}
	})

	t.Run("skips directories", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()
		os.WriteFile(filepath.Join(dir, "note.md"), []byte("x"), 0644)
		os.MkdirAll(filepath.Join(dir, "subdir.md"), 0755) // directory with .md name
		files := discoverMemoryFiles(dir)
		if len(files) != 1 {
			t.Fatalf("expected 1 file, got %d: %v", len(files), files)
		}
		if files[0] != "note.md" {
			t.Errorf("files[0] = %q, want %q", files[0], "note.md")
		}
	})
}

func TestRepoSlugFromRemoteOrDir_FallbackToDirName(t *testing.T) {
	t.Parallel()
	// use a temp dir with no git repo - should fall back to dir name
	dir := t.TempDir()
	got := repoSlugFromRemoteOrDir(dir)
	want := filepath.Base(dir)
	if got != want {
		t.Errorf("repoSlugFromRemoteOrDir(%q) = %q, want %q", dir, got, want)
	}
}

func TestRepoSlugFromRemoteOrDir_HTTPSRemote(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	// init a git repo with an HTTPS remote
	for _, args := range [][]string{
		{"init"},
		{"remote", "add", "origin", "https://github.com/acme/widgets.git"},
	} {
		cmd := exec.Command("git", args...)
		cmd.Dir = dir
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v\n%s", args, err, out)
		}
	}

	got := repoSlugFromRemoteOrDir(dir)
	if got != "acme/widgets" {
		t.Errorf("repoSlugFromRemoteOrDir (HTTPS) = %q, want %q", got, "acme/widgets")
	}
}

func TestRepoSlugFromRemoteOrDir_SSHRemote(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	for _, args := range [][]string{
		{"init"},
		{"remote", "add", "origin", "git@github.com:acme/gadgets.git"},
	} {
		cmd := exec.Command("git", args...)
		cmd.Dir = dir
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v\n%s", args, err, out)
		}
	}

	got := repoSlugFromRemoteOrDir(dir)
	if got != "acme/gadgets" {
		t.Errorf("repoSlugFromRemoteOrDir (SSH) = %q, want %q", got, "acme/gadgets")
	}
}

func TestRepoSlugFromRemoteOrDir_HTTPSNoGitSuffix(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	for _, args := range [][]string{
		{"init"},
		{"remote", "add", "origin", "https://gitlab.com/org/project"},
	} {
		cmd := exec.Command("git", args...)
		cmd.Dir = dir
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v\n%s", args, err, out)
		}
	}

	got := repoSlugFromRemoteOrDir(dir)
	if got != "org/project" {
		t.Errorf("repoSlugFromRemoteOrDir (no .git suffix) = %q, want %q", got, "org/project")
	}
}

func TestFormatAge_Coverage(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name     string
		duration time.Duration
		want     string
	}{
		{"just now", 30 * time.Second, "just now"},
		{"1 minute", 1 * time.Minute, "1m ago"},
		{"multiple minutes", 45 * time.Minute, "45m ago"},
		{"1 hour", 1 * time.Hour, "1h ago"},
		{"multiple hours", 5 * time.Hour, "5h ago"},
		{"1 day", 24 * time.Hour, "1d ago"},
		{"multiple days", 72 * time.Hour, "3d ago"},
		{"zero", 0, "just now"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got := formatAge(tt.duration)
			if got != tt.want {
				t.Errorf("formatAge(%v) = %q, want %q", tt.duration, got, tt.want)
			}
		})
	}
}

func TestSortOtherTeamsByAge_Coverage(t *testing.T) {
	t.Parallel()

	entries := []otherTeamEntry{
		{Slug: "old", Age: "5d ago"},
		{Slug: "newest", Age: "just now"},
		{Slug: "unknown", Age: ""},
		{Slug: "mid", Age: "2h ago"},
	}

	sortOtherTeamsByAge(entries)

	// newest first, unknown last
	expectedOrder := []string{"newest", "mid", "old", "unknown"}
	for i, want := range expectedOrder {
		if entries[i].Slug != want {
			t.Errorf("position %d: got Slug=%q, want %q", i, entries[i].Slug, want)
		}
	}
}

func TestCanonicalAgentType_Coverage(t *testing.T) {
	t.Parallel()
	tests := []struct {
		input string
		want  string
	}{
		{"claude-code", "claude"},
		{"Claude-Code", "claude"},
		{"CLAUDE-CODE", "claude"},
		{"codex", "codex"},
	}
	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			t.Parallel()
			got := canonicalAgentType(tt.input)
			if got != tt.want {
				t.Errorf("canonicalAgentType(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestIsAgentSupported_Coverage(t *testing.T) {
	t.Parallel()
	if !isAgentSupported("claude-code") {
		t.Error("expected claude-code to be supported")
	}
	if isAgentSupported("unknown-agent-xyz") {
		t.Error("expected unknown-agent-xyz to be unsupported")
	}
}

func TestGetAgentSupportNotice_Coverage(t *testing.T) {
	t.Parallel()
	// supported agent should return empty notice
	notice := getAgentSupportNotice("claude-code")
	if notice != "" {
		t.Errorf("expected empty notice for supported agent, got %q", notice)
	}
	// unsupported agent should return non-empty notice
	notice = getAgentSupportNotice("unknown-agent-xyz")
	if notice == "" {
		t.Error("expected non-empty notice for unsupported agent")
	}
}

func TestCodexLifecycleNotification_Coverage(t *testing.T) {
	t.Parallel()
	// non-codex agent should return empty
	got := codexLifecycleNotification("claude-code")
	if got != "" {
		t.Errorf("expected empty for claude-code, got %q", got)
	}
	// codex agent should return a notification
	got = codexLifecycleNotification("codex")
	if got == "" {
		t.Error("expected non-empty notification for codex")
	}
}

func TestBuildCapturePriorGuidance_Coverage(t *testing.T) {
	t.Parallel()
	result := buildCapturePriorGuidance("agent-123")
	if result == nil {
		t.Fatal("expected non-nil guidance")
	}
}

func TestLoadProjectGuidance_ReturnsNil(t *testing.T) {
	t.Parallel()
	// loadProjectGuidance currently always returns nil
	got := loadProjectGuidance(t.TempDir(), "claude-code")
	if got != nil {
		t.Error("expected nil from loadProjectGuidance")
	}
}

func TestCheckTeamContextStaleness_NilTeamContext(t *testing.T) {
	t.Parallel()
	// should not panic on nil input
	checkTeamContextStaleness(nil, "")
}

func TestTeamContextAge_EmptyPath(t *testing.T) {
	t.Parallel()
	got := teamContextAge("")
	if got != "" {
		t.Errorf("expected empty string for empty path, got %q", got)
	}
}

func TestTeamContextAge_NonexistentPath(t *testing.T) {
	t.Parallel()
	got := teamContextAge("/nonexistent/path/that/does/not/exist")
	if got != "" {
		t.Errorf("expected empty string for nonexistent path, got %q", got)
	}
}

func TestTeamContextAge_NoGitRepo(t *testing.T) {
	t.Parallel()
	// directory exists but is not a git repo
	dir := t.TempDir()
	got := teamContextAge(dir)
	if got != "" {
		t.Errorf("expected empty string for non-git dir, got %q", got)
	}
}

func TestTeamContextAge_WithCommit(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	// init repo, create a commit
	for _, args := range [][]string{
		{"init"},
		{"-c", "user.name=Test", "-c", "user.email=test@test.com", "commit", "--allow-empty", "-m", "init"},
	} {
		cmd := exec.Command("git", args...)
		cmd.Dir = dir
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v\n%s", args, err, out)
		}
	}

	got := teamContextAge(dir)
	if got == "" {
		t.Error("expected non-empty age for repo with commit")
	}
	// commit was just made, should be "just now"
	if got != "just now" {
		t.Errorf("expected 'just now' for fresh commit, got %q", got)
	}
}
