"""Pure game state transitions: no I/O, clock reads, or randomness."""
import math
from dataclasses import dataclass
from typing import Optional, Sequence
from .policies import correct_points
from .difficulty import DifficultyPolicy, EloDifficulty
from .questions import Question, QuestionRequest

@dataclass(frozen=True)
class Outcome:
    kind: str
    points: int = 0
    elapsed: float = 0.0


class Game:
    def __init__(self, questions: Sequence[Question], time_limit: float = 15.0,
                 timed: bool = True):
        if not math.isfinite(time_limit) or time_limit <= 0:
            raise ValueError("time_limit must be finite and positive")
        self.questions = tuple(questions)
        if len({q.id for q in self.questions}) != len(self.questions):
            raise ValueError("Question IDs must be unique")
        self.time_limit, self.timed = time_limit, timed
        self.score = self.streak = self.best_streak = self.correct = self.rounds = 0
        self.active: Optional[Question] = None
        self.started_at = 0.0
        self.deadline = math.inf
        self.stopped = False

    @property
    def question_count(self) -> int:
        return len(self.questions)

    @property
    def finished(self) -> bool:
        return self.stopped or self.rounds == self.question_count

    def start_question(self, now: float) -> Question:
        self._validate_start(now)
        return self._activate(self.questions[self.rounds], now)

    def _validate_start(self, now: float) -> None:
        if self.finished or self.active is not None:
            raise ValueError("Cannot start a question in the current state")
        if not math.isfinite(now):
            raise ValueError("Timestamp must be finite")

    def _activate(self, question: Question, now: float) -> Question:
        self.active = question
        self.started_at = now
        self.deadline = now + self.time_limit if self.timed else math.inf
        return self.active

    def expire(self, question_id: int, now: float) -> Outcome:
        if not self._matches(question_id):
            return Outcome("ignored")
        self._validate_time(now)
        if now < self.deadline:
            return Outcome("pending")
        return self._resolve("timeout", now)

    def submit(self, question_id: int, text: str, now: float) -> Outcome:
        if not self._matches(question_id):
            return Outcome("ignored")
        self._validate_time(now)
        if text.strip().lower() in ("q", "quit"):
            self.stop()
            return Outcome("quit")
        if now >= self.deadline:
            return self._resolve("timeout", now)
        try:
            guess = int(text.strip())
        except ValueError:
            return Outcome("invalid")
        return self._resolve("correct" if guess == self.active.answer else "wrong", now)

    def stop(self) -> None:
        self.stopped = True
        self.active = None

    def _matches(self, question_id: int) -> bool:
        return self.active is not None and self.active.id == question_id

    def _validate_time(self, now: float) -> None:
        if not math.isfinite(now) or now < self.started_at:
            raise ValueError("Timestamp must be finite and not before question start")

    def _resolve(self, kind: str, now: float) -> Outcome:
        elapsed = now - self.started_at
        self._on_resolved(self.active, kind)
        points = 0
        if kind == "correct":
            points = correct_points(elapsed, self.time_limit, self.streak, self.timed)
            self.score += points
            self.correct += 1
            self.streak += 1
            self.best_streak = max(self.best_streak, self.streak)
        else:
            self.streak = 0
        self.rounds += 1
        self.active = None
        return Outcome(kind, points, elapsed)

    def _on_resolved(self, question: Question, kind: str) -> None:
        """Extension point invoked only for a matched, terminal outcome."""


class AdaptiveGame(Game):
    """Practice engine selecting the next family after each resolved answer.

    The caller asks request_question(), generates a matching Question externally,
    then calls start_question(now, question). No question is generated by the
    engine. The finite operation schedule is supplied as values, like ranked
    Game's fixed question schedule. Adaptive practice has no ranked eligibility.
    """

    ranked_eligible = False

    def __init__(self, operations: Sequence[str],
                 policy: Optional[DifficultyPolicy] = None,
                 time_limit: float = 15.0, timed: bool = True):
        self.operations = tuple(operations)
        if any(op not in ("+", "-", "*", "/") for op in self.operations):
            raise ValueError("Unsupported operation in adaptive schedule")
        super().__init__((), time_limit=time_limit, timed=timed)
        self.policy = EloDifficulty() if policy is None else policy
        self._request: Optional[QuestionRequest] = None
        self._next_id = 1

    @property
    def question_count(self) -> int:
        return len(self.operations)

    def request_question(self) -> QuestionRequest:
        if self.finished or self.active is not None:
            raise ValueError("Cannot request a question in the current state")
        if self._request is None:
            operation = self.operations[self.rounds]
            level = self.policy.select(operation)
            if type(level) is not int or level < 0:
                raise ValueError("Policy must select a nonnegative integer level")
            self._request = QuestionRequest(self._next_id, operation, level)
            self._next_id += 1
        return self._request

    def start_question(self, now: float, question: Question) -> Question:
        self._validate_start(now)
        request = self.request_question()
        if (question.id != request.id or question.operation != request.operation
                or type(question.level) is not int or question.level != request.level):
            raise ValueError("Question must match the requested ID, operation, and level")
        return self._activate(question, now)

    def _on_resolved(self, question: Question, kind: str) -> None:
        self.policy.update(question.operation, question.level, kind == "correct")
        self._request = None

    def stop(self) -> None:
        super().stop()
        self._request = None

    def restart(self) -> None:
        """Start a fresh run; abandon pending input without training a miss.

        Retain policy configuration and the operation schedule, reset all learned
        ratings and progress, and never reuse question IDs within this instance.
        """
        self.policy.reset()
        super().__init__((), time_limit=self.time_limit, timed=self.timed)
        self._request = None
