package daemon

import (
	"log/slog"
	"os"
	"slices"
	"sync"
	"syscall"
	"time"
)

// Instance status constants.
const (
	StatusActive = "active" // recently received heartbeat
	StatusIdle   = "idle"   // no heartbeat within idle threshold
	StatusStale  = "stale"  // no heartbeat within stale threshold
	StatusExited = "exited" // parent process confirmed dead via kill(pid, 0)
)

// Default instance timing thresholds.
const (
	// IdleThreshold is how long without heartbeat before instance is "idle".
	// Agents typically heartbeat every ~5s, so 30s = missed ~6 heartbeats.
	IdleThreshold = 30 * time.Second

	// StaleThreshold is how long without heartbeat before instance is "stale".
	// Stale instances are candidates for cleanup.
	StaleThreshold = 5 * time.Minute

	// MaxAge is the maximum age of an instance before auto-cleanup.
	// Prevents abandoned instances from accumulating indefinitely.
	MaxAge = 24 * time.Hour

	// CleanupInterval is how often to run the cleanup routine.
	CleanupInterval = 1 * time.Minute

	// MaxInstances caps the number of tracked instances to prevent unbounded growth.
	// When exceeded, oldest stale instances are evicted first.
	MaxInstances = 100
)

// Instance represents an active agent instance.
// Instances are registered when agents connect and tracked via heartbeats.
type Instance struct {
	// ID is the unique instance identifier (e.g., "Oxa7b3").
	// Generated by the agent on startup.
	ID string `json:"id"`

	// AgentType identifies the type of agent (e.g., "claude-code", "cursor").
	AgentType string `json:"agent_type"`

	// StartTime is when the instance was registered.
	StartTime time.Time `json:"start_time"`

	// LastHeartbeat is when the last heartbeat was received.
	LastHeartbeat time.Time `json:"last_heartbeat"`

	// WorkspacePath is the workspace directory the agent is operating in.
	WorkspacePath string `json:"workspace_path"`

	// Status is the computed instance status: "active", "idle", or "stale".
	// Computed from LastHeartbeat relative to current time.
	Status string `json:"status"`

	// ParentPID is the process ID of the parent agent process.
	// Used for instant liveness detection via kill(pid, 0).
	ParentPID int `json:"parent_pid,omitempty"`
}

// IsProcessAlive checks if the parent agent process is still running.
// Uses kill(pid, 0) which checks existence without sending a signal.
// Returns false if no PID was recorded or the process is gone.
func (i *Instance) IsProcessAlive() bool {
	if i.ParentPID <= 0 {
		return false
	}
	proc, err := os.FindProcess(i.ParentPID)
	if err != nil {
		return false
	}
	return proc.Signal(syscall.Signal(0)) == nil
}

// computeStatus determines the instance status based on the last heartbeat.
func (i *Instance) computeStatus(now time.Time) string {
	elapsed := now.Sub(i.LastHeartbeat)
	switch {
	case elapsed < IdleThreshold:
		return StatusActive
	case elapsed < StaleThreshold:
		return StatusIdle
	default:
		return StatusStale
	}
}

// InstanceStore manages active agent instances.
//
// Design principles:
//   - Thread-safe: sync loop and IPC handlers may access concurrently
//   - Bounded: MaxInstances cap prevents unbounded memory growth
//   - Self-cleaning: stale instances are automatically removed
//   - Fast reads: GetActive() is O(n) where n = active instances (typically < 10)
//
// The daemon uses InstanceStore to:
//   - Track which agents are connected (for `ox status`)
//   - Coordinate work across multiple agents
//   - Clean up resources when agents disconnect
type InstanceStore struct {
	mu        sync.RWMutex
	instances map[string]*Instance
	logger    *slog.Logger

	// cleanup goroutine lifecycle
	stopCleanup chan struct{}
	cleanupDone chan struct{}
}

// NewInstanceStore creates a new instance store.
func NewInstanceStore(logger *slog.Logger) *InstanceStore {
	if logger == nil {
		logger = slog.Default()
	}
	return &InstanceStore{
		instances: make(map[string]*Instance),
		logger:    logger,
	}
}

// StartCleanup starts the background cleanup routine.
// Call Stop() to stop the cleanup routine.
func (s *InstanceStore) StartCleanup() {
	s.stopCleanup = make(chan struct{})
	s.cleanupDone = make(chan struct{})

	go func() {
		defer close(s.cleanupDone)
		ticker := time.NewTicker(CleanupInterval)
		defer ticker.Stop()

		for {
			select {
			case <-s.stopCleanup:
				return
			case <-ticker.C:
				s.cleanup()
			}
		}
	}()
}

// Stop stops the background cleanup routine.
func (s *InstanceStore) Stop() {
	if s.stopCleanup != nil {
		close(s.stopCleanup)
		<-s.cleanupDone
	}
}

// cleanup removes stale and expired instances.
func (s *InstanceStore) cleanup() {
	s.mu.Lock()
	defer s.mu.Unlock()

	now := time.Now()
	removed := 0

	for id, inst := range s.instances {
		// remove instances that exceed max age
		if now.Sub(inst.StartTime) > MaxAge {
			delete(s.instances, id)
			removed++
			s.logger.Debug("instance expired by age", "id", id, "age", now.Sub(inst.StartTime))
			continue
		}

		// remove instances whose parent process has exited
		if inst.ParentPID > 0 && !inst.IsProcessAlive() {
			delete(s.instances, id)
			removed++
			s.logger.Debug("instance removed: process exited", "id", id, "pid", inst.ParentPID)
			continue
		}

		// remove stale instances (no heartbeat for a while)
		if inst.computeStatus(now) == StatusStale {
			delete(s.instances, id)
			removed++
			s.logger.Debug("instance removed as stale", "id", id, "last_heartbeat", inst.LastHeartbeat)
		}
	}

	if removed > 0 {
		s.logger.Debug("instance cleanup complete", "removed", removed, "remaining", len(s.instances))
	}
}

// Register adds or updates an instance.
// If an instance with the same ID exists, it is updated.
func (s *InstanceStore) Register(inst *Instance) {
	if inst == nil || inst.ID == "" {
		return
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	// check if instance exists (update) vs new (add)
	existing, exists := s.instances[inst.ID]
	if exists {
		// update existing instance
		if !inst.LastHeartbeat.IsZero() {
			existing.LastHeartbeat = inst.LastHeartbeat
		} else if existing.LastHeartbeat.IsZero() {
			existing.LastHeartbeat = time.Now()
		}
		if inst.WorkspacePath != "" {
			existing.WorkspacePath = inst.WorkspacePath
		}
		if inst.AgentType != "" {
			existing.AgentType = inst.AgentType
		}
		if inst.ParentPID > 0 {
			existing.ParentPID = inst.ParentPID
		}
		s.logger.Debug("instance updated", "id", inst.ID)
		return
	}

	// enforce max instances by evicting oldest stale instance
	if len(s.instances) >= MaxInstances {
		s.evictOldestStale()
	}

	// still at capacity? evict oldest instance regardless of status
	if len(s.instances) >= MaxInstances {
		s.evictOldest()
	}

	// add new instance
	if inst.StartTime.IsZero() {
		inst.StartTime = time.Now()
	}
	if inst.LastHeartbeat.IsZero() {
		inst.LastHeartbeat = time.Now()
	}
	s.instances[inst.ID] = inst
	s.logger.Info("instance registered", "id", inst.ID, "agent_type", inst.AgentType, "workspace", inst.WorkspacePath)
}

// evictOldestStale removes the oldest stale instance (must hold lock).
func (s *InstanceStore) evictOldestStale() {
	now := time.Now()
	var oldestID string
	var oldestTime time.Time

	for id, inst := range s.instances {
		if inst.computeStatus(now) == StatusStale {
			if oldestID == "" || inst.LastHeartbeat.Before(oldestTime) {
				oldestID = id
				oldestTime = inst.LastHeartbeat
			}
		}
	}

	if oldestID != "" {
		delete(s.instances, oldestID)
		s.logger.Debug("evicted stale instance to make room", "id", oldestID)
	}
}

// evictOldest removes the oldest instance regardless of status (must hold lock).
func (s *InstanceStore) evictOldest() {
	var oldestID string
	var oldestTime time.Time

	for id, inst := range s.instances {
		if oldestID == "" || inst.LastHeartbeat.Before(oldestTime) {
			oldestID = id
			oldestTime = inst.LastHeartbeat
		}
	}

	if oldestID != "" {
		delete(s.instances, oldestID)
		s.logger.Debug("evicted oldest instance to make room", "id", oldestID)
	}
}

// Heartbeat updates the last heartbeat time for an instance.
// If the instance doesn't exist, this is a no-op.
// Use Register() to create new instances.
func (s *InstanceStore) Heartbeat(id string) {
	if id == "" {
		return
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	inst, exists := s.instances[id]
	if !exists {
		return
	}

	inst.LastHeartbeat = time.Now()
	s.logger.Debug("instance heartbeat", "id", id)
}

// Deregister removes an instance.
// No-op if the instance doesn't exist.
func (s *InstanceStore) Deregister(id string) {
	if id == "" {
		return
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	if _, exists := s.instances[id]; exists {
		delete(s.instances, id)
		s.logger.Info("instance deregistered", "id", id)
	}
}

// Get retrieves an instance by ID.
// Returns nil if not found.
func (s *InstanceStore) Get(id string) *Instance {
	if id == "" {
		return nil
	}

	s.mu.RLock()
	defer s.mu.RUnlock()

	inst, exists := s.instances[id]
	if !exists {
		return nil
	}

	// return copy with computed status
	copy := *inst
	copy.Status = inst.computeStatus(time.Now())
	return &copy
}

// GetActive returns all instances that are not stale.
// Includes both "active" and "idle" instances.
// Returns a copy sorted by last heartbeat (most recent first).
func (s *InstanceStore) GetActive() []*Instance {
	s.mu.RLock()
	defer s.mu.RUnlock()

	now := time.Now()
	result := make([]*Instance, 0, len(s.instances))

	for _, inst := range s.instances {
		status := inst.computeStatus(now)
		if status != StatusStale {
			copy := *inst
			copy.Status = status
			result = append(result, &copy)
		}
	}

	// sort by last heartbeat descending (most recent first)
	slices.SortFunc(result, func(a, b *Instance) int {
		return b.LastHeartbeat.Compare(a.LastHeartbeat)
	})

	return result
}

// GetStale returns instances that haven't received a heartbeat within the threshold.
// These are candidates for cleanup.
// Returns a copy sorted by last heartbeat (oldest first).
func (s *InstanceStore) GetStale(threshold time.Duration) []*Instance {
	s.mu.RLock()
	defer s.mu.RUnlock()

	now := time.Now()
	result := make([]*Instance, 0)

	for _, inst := range s.instances {
		if now.Sub(inst.LastHeartbeat) >= threshold {
			copy := *inst
			copy.Status = StatusStale
			result = append(result, &copy)
		}
	}

	// sort by last heartbeat ascending (oldest first)
	slices.SortFunc(result, func(a, b *Instance) int {
		return a.LastHeartbeat.Compare(b.LastHeartbeat)
	})

	return result
}

// GetAll returns all instances regardless of status.
// Returns a copy sorted by start time (oldest first).
func (s *InstanceStore) GetAll() []*Instance {
	s.mu.RLock()
	defer s.mu.RUnlock()

	now := time.Now()
	result := make([]*Instance, 0, len(s.instances))

	for _, inst := range s.instances {
		copy := *inst
		copy.Status = inst.computeStatus(now)
		result = append(result, &copy)
	}

	// sort by start time ascending (oldest first)
	slices.SortFunc(result, func(a, b *Instance) int {
		return a.StartTime.Compare(b.StartTime)
	})

	return result
}

// Count returns the total number of tracked instances.
func (s *InstanceStore) Count() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return len(s.instances)
}

// ActiveCount returns the number of active (non-stale) instances.
func (s *InstanceStore) ActiveCount() int {
	s.mu.RLock()
	defer s.mu.RUnlock()

	now := time.Now()
	count := 0
	for _, inst := range s.instances {
		if inst.computeStatus(now) != StatusStale {
			count++
		}
	}
	return count
}

// Backward compatibility aliases for SessionStaleThreshold
// TODO: Remove after updating all consumers
const SessionStaleThreshold = StaleThreshold
